export const JOB_TITLES = [
  'Accountant',
  'Cloud Architect',
  'Cloud Cost Engineer',
  'Cloud Developer',
  'Cloud Engineer',
  'Configuration Manager',
  'Cyber Security Architect',
  'Cyber Security Engineer',
  'Data Architect',
  'Data Engineer',
  'Data Scientist',
  'Devops Engineer',
  'HR Manager',
  'IT Support',
  'Network Engineer',
  'Office Manager',
  'Project Integrator',
  'Project Manager',
  'Software Architect',
  'Software Developer',
  'Storage Engineer',
  'Systems Administrator',
  'System Engineer',
  'Test Engineer',
  'QA Automated Test Engineer',
  'Windows Engineer'
];
