/**
 * This array is from data taken from this article on Wikipedia:
 * https://en.wikipedia.org/wiki/List_of_academic_fields
 */
export let majorsAndMinors = [
  'Abnormal Psychology',
  'Abrahamic Religions',
  'Accelerator Physics',
  'Accompanying',
  'Accounting',
  'Accounting Information Systems',
  'Accounting Research',
  'Accounting Scholarship',
  'Acoustical Engineering',
  'Acoustics ',
  'Acquired Taste',
  'Acting',
  'Activism',
  'Actuarial Science',
  'Administrative Law',
  'Admiralty Law',
  'Advertising',
  'Aerial',
  'Aerial Archaeology',
  'Aerobics',
  'Aerobics',
  'Aerobiology',
  'Aerodynamics',
  'Aeronautics',
  'Aeronautics',
  'Aerospace Architecture',
  'Aerospace Engineering',
  'Aerospace Engineering',
  'Aerospace Manufacturing',
  'Aerospace Physiology',
  'Aesthetics ',
  'Affect Control Theory',
  'Affine Geometry',
  'African Archaeology',
  'African History',
  'African Religions',
  'African Studies',
  'Aftertaste',
  'Agnosticism',
  'Agricultural Economics',
  'Agricultural Economics',
  'Agricultural Education',
  'Agricultural Engineering',
  'Agricultural Engineering',
  'Agricultural Policy',
  'Agriculture',
  'Agrochemistry',
  'Agroecology',
  'Agroecology',
  'Agrology',
  'Agronomy',
  'Agrophysics',
  'Air',
  'Algebra ',
  'Algebraic (Symbolic) Computation',
  'Algebraic Geometry',
  'Algebraic Number Theory',
  'Algebraic Topology',
  'Algorithms',
  'Alternative Education',
  'Alternative Medicine',
  'Amateur Astronomy',
  'American History',
  'American Literature',
  'American Politics',
  'American Studies',
  'Amphibious Warfare',
  'Analysis',
  'Analytic Number Theory',
  'Analytic Philosophy',
  'Analytical Chemistry',
  'Analytical Dynamics',
  'Analytical Mechanics',
  'Analytical Sociology',
  'Anarchism ',
  'Anarchist Economics',
  'Anatomical Pathology',
  'Anatomy',
  'Ancient',
  'Ancient Chinese History ',
  'Ancient Egyptian History ',
  'Ancient Egyptian Religion',
  'Ancient Greek History ',
  'Ancient Middle Eastern History',
  'Ancient Roman History ',
  'Ancient History',
  'Ancient Philosophy',
  'Androcentrism',
  'Andrology',
  'Animal Communication',
  'Animal Communications',
  'Animal Husbandry (Animal Science)',
  'Animal Law/Animal Rights',
  'Animal Rights',
  'Animation',
  'Anthracology',
  'Anthropological Criminology',
  'Anthropological Linguistics',
  'Anthropology',
  'Anthropology Of Art',
  'Anthropology Of Development',
  'Anthropology Of Institutions',
  'Anthropology Of Media',
  'Anthropology Of Religion',
  'Anthrozoology',
  'Apiology',
  'Apologetics',
  'Appalachian Studies',
  'Appetite',
  'Applied Anthropology',
  'Applied Economics',
  'Applied Ethics',
  'Applied Linguistics',
  'Applied Mathematics',
  'Applied Mechanics',
  'Applied Philosophy',
  'Applied Physics',
  'Applied Physics ',
  'Applied Psychology',
  'Applied Sociology',
  'Approximation Theory',
  'Aquaculture',
  'Arachnology',
  'Arcade Game',
  'Archaeo-Optics',
  'Archaeoacoustics',
  'Archaeoastronomy',
  'Archaeoastronomy',
  'Archaeogenetics',
  'Archaeogeography',
  'Archaeological Culture',
  'Archaeological Theory',
  'Archaeology',
  'Archaeology Of China',
  'Archaeology Of Israel',
  'Archaeology Of Religion And Ritual',
  'Archaeology Of The Americas',
  'Archaeology Of Trade',
  'Archaeometry',
  'Archaeomythology',
  'Architectural Analytics',
  'Architectural Analytics',
  'Architectural Engineering',
  'Architectural Sociology',
  'Architecture ',
  'Architecture And Design',
  'Archival Science',
  'Archivist',
  'Area Studies',
  'Argentine History',
  'Aristotelianism',
  'Arithmetic',
  'Arithmetic Combinatorics',
  'Armor',
  'Arms Control',
  'Arms Race',
  'Art Education',
  'Artificial Intelligence ',
  'Artificial Neural Network',
  'Artillery',
  'Artillery',
  'Artisanal Food',
  'Asian History',
  'Asian Psychology',
  'Asian Studies',
  'Assassination',
  'Assignment Problem',
  'Assyriology',
  'Asteroid-Impact Avoidance',
  'Astrobiology',
  'Astrobotany',
  'Astrochemistry',
  'Astrochemistry',
  'Astrodynamics',
  'Astrometry',
  'Astronautics',
  'Astronautics',
  'Astronomy',
  'Astrophysical Plasma',
  'Astrophysics',
  'Astrophysics',
  'Asymmetric Warfare',
  'Atheism ',
  'Athletic Director',
  'Athletic Training',
  'Atmospheric Chemistry',
  'Atmospheric Electricity',
  'Atmospheric Physics',
  'Atmospheric Science',
  'Atomic Physics',
  'Atomic, Molecular, And Optical Physics',
  'Attrition',
  'Audio Game',
  'Australian Archaeology',
  'Australian History',
  'Australian Studies',
  'Automata Theory (Formal Languages)',
  'Automated Reasoning',
  'Automotive Engineering',
  'Aviation Archaeology',
  'Aztec History',
  'Balkan History',
  'Ballistics',
  'Bariatric Surgery',
  'Batoning',
  'Battle',
  'Battlefield Archaeology',
  'Battlespace',
  'Beekeeping (Apiculture)',
  'Behavioral Geography',
  'Behavioral Neuroscience',
  'Behavioral Sociology',
  'Behavioural Economics',
  'Behavioural Genetics',
  'Biblical Hebrew',
  'Biblical Archaeology',
  'Biblical Studies/Sacred Scripture',
  'Bibliographic Databases',
  'Bibliometrics',
  'Bilingual Education',
  'Bioarchaeology',
  'Biocatalysts',
  'Biochemical Engineering',
  'Biochemical Systems Theory',
  'Biochemistry ',
  'Biochemistry ',
  'Biocultural Anthropology',
  'Biocybernetics',
  'Bioeconomics',
  'Bioengineering',
  'Bioethics',
  'Biogeography',
  'Biogeophysics',
  'Bioinformatics',
  'Biological',
  'Biological Anthropology',
  'Biological Psychology',
  'Biological Systems Engineering',
  'Biological Systems Engineering',
  'Biology',
  'Biomaterials',
  'Biomechanical Engineering',
  'Biomechanics',
  'Biomechanics / Sports Biomechanics',
  'Biomedical Engineering',
  'Biomolecular Engineering',
  'Bionics',
  'Biophysics ',
  'Biophysics ',
  'Biostatistics',
  'Biotechnology ',
  'Black Holes',
  'Black Psychology',
  'Black Studies',
  'Block Design And Analysis Of Variance',
  'Bookmobile',
  'Bootstrap (Statistics)',
  'Botany ',
  'Brazilian History',
  'British History',
  'British Literature',
  'Broadcast Journalism',
  'Brownian Dynamics',
  'Buddhism ',
  'Bushcraft',
  'Business',
  'Business',
  'Business English',
  'Business Administration',
  'Business Analysis',
  'Business Economics',
  'Business Ethics',
  'Business Ethics',
  'Business Law',
  'Business Law',
  'Business Studies',
  'Calceology',
  'Calculus ',
  'Campaigning',
  'Canadian History',
  'Canadian Politics',
  'Canadian Studies',
  'Canon Law',
  'Canon Law',
  'Caodaism',
  'Carcinology',
  'Cardiac Electrophysiology',
  'Cardiology',
  'Cardiothoracic Surgery',
  'Cartography ',
  'Cataloging',
  'Catalysis',
  'Catalysts',
  'Categorization',
  'Category Theory',
  'Cavalry',
  'Cavalry',
  'Celestial Mechanics',
  'Celestial Mechanics',
  'Cell Biology ',
  'Celtic Studies',
  'Central Asian Studies',
  'Ceramic Engineering',
  'Cetology',
  'Chamber Music',
  'Chaos Theory',
  'Chaos Theory',
  'Charge',
  'Chemical',
  'Chemical Biology',
  'Chemical Engineering',
  'Chemical Engineering ',
  'Chemical Physics',
  'Chemical Physics',
  'Cheminformatics',
  'Chemistry',
  'Chemistry Education',
  'Child Psychopathology',
  'Child Welfare',
  "Children'S Geographies",
  'Chinese Folk Religion',
  'Chinese History',
  'Chinese Sociology',
  'Chondogyo',
  'Choral Conducting',
  'Choreography',
  'Christian Ethics',
  'Christian Theology ',
  'Christianity ',
  'Chronobiology',
  'Church History',
  'Church Music',
  'Citation Analysis',
  'Civics',
  'Civil Defense',
  'Civil Engineering',
  'Civil Law',
  'Civil Procedure',
  'Civil Service',
  'Clandestine Operation',
  'Classical Archaeology',
  'Classical Language',
  'Classical Mechanics',
  'Classical Physics',
  'Classics ',
  'Classification',
  'Cleaning',
  'Climate Change Policy',
  'Climatology',
  'Clinical Biochemistry',
  'Clinical Immunology',
  'Clinical Laboratory Sciences/Clinical Pathology/Laboratory Medicine',
  'Clinical Microbiology',
  'Clinical Neuropsychology',
  'Clinical Pathology',
  'Clinical Physiology',
  'Clinical Psychology',
  'Cloud Computing',
  'Coastal Engineering',
  'Coastal Geography',
  'Coastal Management',
  'Coding Theory',
  'Cognitive Anthropology',
  'Cognitive Archaeology',
  'Cognitive Biology',
  'Cognitive Psychology',
  'Cognitive Science',
  'Cold War (General Term)',
  'Collateral Damage',
  'Collection Management Policy',
  'Collection Management',
  'Collections Care',
  'Collective Bargaining',
  'Collective Behavior',
  'Colombian History',
  'Combat',
  'Combinatorics ',
  'Command And Control',
  'Commercial Policy',
  'Common Law',
  'Communication Design',
  'Communication Physics',
  'Communication Studies',
  'Communications System',
  'Community Informatics',
  'Community Informatics',
  'Community Organizing',
  'Community Practice',
  'Community Psychology',
  'Commutative Algebra',
  'Compact Objects',
  'Comparative Anatomy',
  'Comparative Education',
  'Comparative Law',
  'Comparative Literature',
  'Comparative Politics',
  'Comparative Psychology',
  'Comparative Religion',
  'Comparative Sociology',
  'Competition Law',
  'Compilers',
  'Complex Analysis',
  'Complex System',
  'Complex Systems',
  'Complexity Economics',
  'Composition Studies',
  'Compressible Flow',
  'Computability Theory',
  'Computational Neuroscience',
  'Computational Archaeology',
  'Computational Astrophysics',
  'Computational Biology',
  'Computational Biology (Bioinformatics)',
  'Computational Chemistry',
  'Computational Chemistry',
  'Computational Complexity Theory',
  'Computational Complexity Theory',
  'Computational Economics',
  'Computational Economics',
  'Computational Finance',
  'Computational Fluid Dynamics',
  'Computational Geometry',
  'Computational Linguistics',
  'Computational Mathematics',
  'Computational Mathematics',
  'Computational Neuroscience',
  'Computational Number Theory',
  'Computational Physics',
  'Computational Physics',
  'Computational Sociology',
  'Computational Sociology',
  'Computational Statistics',
  'Computational Systems Biology',
  'Computer Information Systems',
  'Computer Security & Information Assurance',
  'Computer Architecture',
  'Computer Communications (Networks)',
  'Computer Engineering ',
  'Computer Graphics',
  'Computer Program',
  'Computer Programming',
  'Computer Science',
  'Computer Science',
  'Computer Security And Reliability',
  'Computer Vision ',
  'Computer-Aided Engineering',
  'Computing In Mathematics, Natural Sciences, Engineering, And Medicine',
  'Computing In Social Sciences, Arts, Humanities, And Professions',
  'Conceptual Systems',
  'Conchology',
  'Concurrency Theory',
  'Concurrent Programming',
  'Condensed Matter Physics',
  'Conducting',
  'Conflict Archaeology',
  'Conflict Theory',
  'Confucianism',
  'Conservation And Restoration Of Cultural Heritage',
  'Conservation Biology',
  'Conservation Biology',
  'Conservation Psychology',
  'Conservation Science',
  'Conspiracy Theory',
  'Constitutional Law',
  'Construction',
  'Consumer Economics',
  'Consumer Education',
  'Consumer Psychology',
  'Containment',
  'Contemporary Archaeology',
  'Contemporary Philosophy',
  'Continental Philosophy',
  'Continuum Mechanics',
  'Continuum Mechanics',
  'Contract Law',
  'Control Engineering',
  'Control Engineering',
  'Control Systems',
  'Control Systems Engineering',
  'Control Theory',
  'Control Theory',
  'Conventional',
  'Convex Geometry',
  'Cooking',
  'Cooperative Learning',
  'Corporate Law',
  'Corporations',
  'Corrections',
  'Corrections',
  'Corrosion Engineering',
  'Cosmetology',
  'Cosmic-Ray Astronomy',
  'Cosmochemistry',
  'Cosmochemistry',
  'Cosmology',
  'Counseling Psychology',
  'Counselor Education',
  'Counter-Attack',
  'Counter-Insurgency',
  'Counter-Intelligence',
  'Counter-Offensive',
  'Counter-Terrorism',
  'Covert Operation',
  'Craft',
  'Creative Nonfiction',
  'Creative Writing',
  'Criminal Justice ',
  'Criminal Justice ',
  'Criminal Law',
  'Criminal Procedure',
  'Criminal Psychology',
  'Criminology/Criminal Justice ',
  'Critical Management Studies',
  'Critical Pedagogy',
  'Critical Sociology',
  'Critical Theory ',
  'Cross-Cultural Studies',
  'Cryobiology',
  'Cryogenics',
  'Cryptanalysis',
  'Cryptography',
  'Cryptography',
  'Crystallography',
  'Cuban History',
  'Cuisine',
  'Culinary Arts',
  'Culinary Arts',
  'Culinary Arts',
  'Culinary Tourism',
  'Cultural Anthropology',
  'Cultural Geography',
  'Cultural Policy',
  'Cultural Psychology',
  'Cultural Sociology',
  'Cultural Studies',
  'Cultural Studies',
  'Culturology',
  'Curator',
  'Curriculum And Instruction',
  'Cyber',
  'Cybernetics',
  'Cyberwarfare',
  'Cyborg Anthropology',
  'Cytogenetics',
  'Cytohematology',
  'Cytology ',
  'Dance ',
  'Dance Notation',
  'Danish History',
  'Daoism ',
  'Data Archaeology',
  'Data Management',
  'Data Mining',
  'Data Mining',
  'Data Modeling',
  'Data Storage',
  'Data Structures',
  'Database',
  'Database ',
  'Database Management',
  'Deception',
  'Decision Analysis',
  'Decision Science',
  'Decision Theory',
  'Decontamination',
  'Decorative Arts',
  'Defense Industry',
  'Defensive',
  'Delicacy',
  'Demography',
  'Demography/Population',
  'Dendrochronology',
  'Dental Hygiene And Epidemiology',
  'Dental Surgery',
  'Dentistry ',
  'Deontic Logic',
  'Dermatology',
  'Dermatology',
  'Dermatopathology',
  'Design Of Experiments',
  'Determinism And Free Will',
  'Development Economics',
  'Development Geography',
  'Developmental Biology',
  'Developmental Psychology',
  'Developmental Systems Theory',
  'Diachronic Linguistics (Or Historical Linguistics)',
  'Diet',
  'Differential Algebra',
  'Differential Psychology',
  'Differential Topology',
  'Digital Anthropology',
  'Digital Archaeology',
  'Digital Culture',
  'Digital Economy',
  'Digital Humanities (Humanities Computing)',
  'Digital Journalism',
  'Digital Media',
  'Digital Physics',
  'Digital Preservation',
  'Digital Sociology',
  'Directing',
  'Disarmament',
  'Disaster Research',
  'Disaster Response',
  'Discourse Analysis',
  'Discrete Geometry',
  'Dissemination',
  'Distance Education',
  'Distributed Algorithms',
  'Distributed Computing',
  'Distributed Database',
  'Divinity',
  'Doctrine',
  'Doctrine',
  'Dogmatic Theology',
  'Domestic Policy',
  'Doxastic Logic',
  'Dramaturgical Sociology',
  'Dramaturgy',
  'Drawing ',
  'Drug Policy',
  'Drug Policy Reform',
  'Dutch History',
  'Dynamic Programming',
  'Dynamical Systems',
  'Dynamical Systems',
  'Dynamics',
  'E-Business',
  'Early Childhood Education',
  'Early Modern',
  'Early Music',
  'Earth Sciences',
  'Earth Systems Engineering And Management',
  'Earthquake Engineering',
  'East Asian Religions',
  'East Asian Studies',
  'Eastern Philosophy',
  'Ecclesiology',
  'Ecological Anthropology',
  'Ecological Economics',
  'Ecological Engineering',
  'Ecological Psychology',
  'Ecological Systems Theory',
  'Ecology',
  'Ecology ',
  'Econometrics',
  'Econometrics',
  'Economic',
  'Economic Anthropology',
  'Economic Development',
  'Economic Geography',
  'Economic Geography',
  'Economic History',
  'Economic History',
  'Economic Policy',
  'Economic Sector',
  'Economic Sociology',
  'Economic Sociology',
  'Economic Sociology/Socioeconomics',
  'Economic Systems',
  'Economic Value',
  'Economics',
  'Econophysics',
  'Ecosystem Ecology',
  'Edaphology',
  'Education',
  'Education And Training',
  'Education Policy',
  'Educational Leadership',
  'Educational Philosophy',
  'Educational Psychology',
  'Educational Psychology',
  'Educational Sociology',
  'Educational Technology',
  'Egyptian History',
  'Egyptology',
  'Electrical Engineering',
  'Electricity',
  'Electrochemistry',
  'Electrokinetics',
  'Electromagnetism',
  'Electronic',
  'Electronic Engineering',
  'Electronic Game',
  'Electronic Media',
  'Electronics',
  'Electrostatic',
  'Elementary Education',
  'Embryology',
  'Emergency Management',
  'Emergency Medicine ',
  'Emergency Services',
  'Empirical Sociology',
  'Endemic Warfare',
  'Endocrinology',
  'Endocrinology',
  'Endodontics',
  'Energy Economics',
  'Energy Policy',
  'Engineering And Technology',
  'Engineering Cybernetics',
  'Engineering Geology',
  'Engineering Physics',
  'Engineering Physics',
  'Engineers',
  'English Literature',
  'English Studies',
  'Enology',
  'Enterprise Systems Engineering',
  'Entomology',
  'Entomology',
  'Entrepreneurial Economics',
  'Entrepreneurship',
  'Entrepreneurship',
  'Environmental Humanities',
  'Environmental Anthropology',
  'Environmental Archaeology',
  'Environmental Chemistry',
  'Environmental Chemistry',
  'Environmental Communication',
  'Environmental Economics',
  'Environmental Engineering',
  'Environmental Ethics',
  'Environmental Geography',
  'Environmental History',
  'Environmental Law',
  'Environmental Management',
  'Environmental Policy',
  'Environmental Policy',
  'Environmental Psychology',
  'Environmental Science',
  'Environmental Sociology',
  'Environmental Studies And Forestry',
  'Epidemiology',
  'Epistemology ',
  'Ergodic Theory',
  'Ergonomics',
  'Ergonomics',
  'Ergonomics ',
  'Escapology',
  'Esotericism',
  'Espionage',
  'Ethics ',
  'Ethnic And Cultural Studies',
  'Ethnic Studies',
  'Ethnoarchaeology',
  'Ethnobiology',
  'Ethnobotany',
  'Ethnobotany',
  'Ethnochoreology',
  'Ethnoecology',
  'Ethnography',
  'Ethnohistory',
  'Ethnolinguistics',
  'Ethnology',
  'Ethnology',
  'Ethnomethodology',
  'Ethnomuseology',
  'Ethnomusicology',
  'Ethnomusicology',
  'Ethnozoology',
  'Ethology',
  'Etruscology',
  'Etymology',
  'Euclidean Geometry',
  'European Archaeology',
  'European History',
  'European Studies',
  'European Studies',
  'Evolution ',
  'Evolutionary Anthropology',
  'Evolutionary Economics',
  'Evolutionary Psychology',
  'Evolutionary Sociology',
  'Exercise Physiology',
  'Exercise Physiology',
  'Exoplanetology',
  'Experimental Archaeology',
  'Experimental Economics',
  'Experimental Physics',
  'Experimental Psychology',
  'Expert Systems',
  'Extragalactic Astronomy',
  'Family And Consumer Science',
  'Family Law',
  'Family Psychology',
  'Family Systems Theory',
  'Fashion Design',
  'Fault-Tolerant Computing',
  'Federal Law',
  'Feminine Psychology',
  'Feminine Psychology',
  'Feminism',
  'Feminist Anthropology',
  'Feminist Archaeology',
  'Feminist Economics',
  'Feminist Geography',
  'Feminist Philosophy',
  'Feminist Philosophy',
  'Feminist Sociology',
  'Feminist Theory',
  'Feminity',
  'Femtochemistry',
  'Fiction Writing ',
  'Field Ministry',
  'Field Theory',
  'Figurational Sociology',
  'File Dynamics',
  'Film ',
  'Film ',
  'Film Classification',
  'Film Criticism',
  'Film Genre',
  'Film Preservation',
  'Film Studies',
  'Film Studies',
  'Film Theory',
  'Filmmaking',
  'Finance ',
  'Financial Econometrics',
  'Financial Economics',
  'Fine Arts',
  'Finite Element Analysis',
  'Finite Geometry',
  'Finnish History',
  'Fire Ecology (Wildland Fire Management)',
  'Fire Safety (Structural Fire Protection)',
  'Fiscal Policy',
  'Fisheries Management',
  'Five Laws Of Library Science',
  'Flavor',
  'Flavor',
  'Flight Dynamics',
  'Flow Chemistry',
  'Fluid Dynamics',
  'Fluid Kinematics',
  'Fluid Mechanics',
  'Fluid Mechanics',
  'Fluid Statics',
  'Folklore',
  'Food Choice',
  'Food Engineering',
  'Food Engineering',
  'Food Pairing',
  'Food Photography',
  'Food Policy',
  'Food Preparation',
  'Food Presentation',
  'Food Safety',
  'Food Science',
  'Food Security',
  'Food Studies',
  'Foodservice Management',
  'Foreign Policy',
  'Forensic Anthropology',
  'Forensic Archaeology',
  'Forensic Astronomy',
  'Forensic Developmental Psychology',
  'Forensic Entomology',
  'Forensic Pathology',
  'Forensic Psychology',
  'Forensic Science ',
  'Forgery',
  'Formal Methods (Formal Verification)',
  'Formal Methods (Formal Verification)',
  'Formal Sciences',
  'Fourier Analysis',
  'Fourth-Generation Warfare',
  'Foxhole',
  'Fractal Geometry',
  'Fractional Dynamics',
  'Fracture Mechanics',
  'French History',
  'Functional Analysis',
  'Functional Programming',
  'Functionalism',
  'Futures Studies ',
  'Fuzzy Logic',
  'Galactic Astronomy',
  'Galaxy Formation And Evolution',
  'Galois Geometry',
  'Game Design',
  'Game Studies **',
  'Game Theory',
  'Game Theory',
  'Gamma-Ray Astronomy',
  'Gas Mechanics',
  'Gastroenterology',
  'Gastronomy',
  'Gemology',
  'Gender And Sexuality Studies',
  'Gender Archaeology',
  'Gender Dysphoria',
  'Gender History',
  'Gender Identity',
  'Gender Role',
  'Gender Studies/Gender Theory',
  'Genderqueer',
  'Gene-Culture Coevolution',
  'General Practice',
  'General Relativity',
  'General Systems Theory',
  'General Topology',
  'Genetics ',
  'Geoarchaeology',
  'Geobiology',
  'Geobiology',
  'Geochemistry',
  'Geochemistry',
  'Geodesy',
  'Geodesy',
  'Geodynamics',
  'Geography',
  'Geography ',
  'Geology ',
  'Geomagnetism',
  'Geometric Number Theory',
  'Geometric Topology',
  'Geometrical Optics',
  'Geometry ',
  'Geomorphology',
  'Geomorphology',
  'Geophysics ',
  'Geophysics ',
  'Geopolitics (Political Geography)',
  'Geotechnical Engineering',
  'Geriatrics',
  'German History',
  'German Studies',
  'Gerontology',
  'Gerontology',
  'Glaciology',
  'Glaciology',
  'Glyptology',
  'Gnosticism',
  'Goal',
  'Gourmet',
  'Governmental Affairs',
  'Grammar',
  'Grand Strategy',
  'Graph Theory',
  'Graphic Arts',
  'Graphic Design',
  'Gravitational Astronomy',
  'Gravitational Wave Astronomy',
  'Great Ages Archaeology',
  'Green Chemistry',
  'Green Economics',
  'Grid Computing',
  'Group Psychology',
  'Group Theory',
  'Growth Economics',
  'Guerrilla Warfare',
  'Gynaecology',
  'Gynocentrism',
  'Haemostasiology',
  'Hamiltonian Mechanics',
  'Harmonic Analysis',
  'Health Geography',
  'Health Informatics',
  'Health Informatics/Clinical Informatics',
  'Health Policy',
  'Health Psychology',
  'Heat Transfer',
  'Helioseismology',
  'Helminthology',
  'Hematology',
  'Hematopathology',
  'Hepatology',
  'Hermeneutics',
  'Herpetology',
  'Heterosexism',
  'High-Energy Astronomy',
  'High-Energy Astrophysics',
  'High-Performance Computing',
  'Higher Education',
  'Highway Engineering',
  'Highway Safety',
  'Hindu Ethics',
  'Hinduism ',
  'Histochemistry',
  'Histology',
  'Histology',
  'Histopathology',
  'Historic Preservation',
  'Historic Preservation',
  'Historical Archaeology',
  'Historical Geography',
  'Historical Linguistics',
  'Historical Musicology',
  'Historical Sociology',
  'Historical Theology',
  'History',
  'History',
  'History Of Archaeology',
  'History Of Computer Hardware',
  'History Of Computer Science ',
  'History Of Dance',
  'History Of Library Science',
  'History Of Linguistics',
  'History Of Literature',
  'History Of Philosophy',
  'History Of The Roman Empire',
  'History Of The Roman Republic',
  'Hoax',
  'Homeokinetics',
  'Homiletics',
  'Homological Algebra',
  'Honors Interdisciplinary Studies',
  'Horticulture',
  'Household Archaeology',
  'Housing',
  'Housing Policy',
  'Human Services',
  'Human Anatomy ',
  'Human Behavioral Ecology',
  'Human Biology',
  'Human Development Theory',
  'Human Ecology',
  'Human Ecology',
  'Human Evolution',
  'Human Geography',
  'Human Physical Performance And Recreation',
  'Human Physiology',
  'Human Resources',
  'Human Resources Management',
  'Human Sexual Behavior',
  'Human Sexuality ',
  'Human Spaceflight',
  'Human-Computer Interaction',
  'Humanism ',
  'Humanistic Informatics',
  'Humanistic Psychology',
  'Humanistic Sociology',
  'Human▒Computer Interaction',
  'Hydraulic Engineering',
  'Hydraulics',
  'Hydrodynamics',
  'Hydrodynamics',
  'Hydrogenation',
  'Hydrogeology',
  'Hydrology ',
  'Hydrology ',
  'Hydrology/Hydrography',
  'I-Kuan Tao',
  'Icelandic History',
  'Ichthyology ',
  'Image Processing',
  'Immigration Policy',
  'Immunochemistry',
  'Immunology ',
  'Imperative Programming',
  'Implantology',
  'Inca History',
  'Incomes Policy',
  'Indexer',
  'Indian History ',
  'Indian Religions',
  'Indigenous Psychology',
  'Indo-European Studies',
  'Indology (Indian Studies)',
  'Indonesian History',
  'Industrial',
  'Industrial And Labor Relations',
  'Industrial Archaeology',
  'Industrial Design (Product Design)',
  'Industrial Engineering',
  'Industrial Organization',
  'Industrial Organization',
  'Industrial Policy',
  'Industrial Sociology',
  'Infantry',
  'Infectious Disease',
  'Infiltration',
  'Infographics',
  'Informatics',
  'Information',
  'Information Architecture',
  'Information Architecture',
  'Information Broker',
  'Information Economics',
  'Information Literacy',
  'Information Management',
  'Information Retrieval',
  'Information Retrieval',
  'Information Science ',
  'Information Science ',
  'Information Systems',
  'Information Systems (Business Informatics)',
  'Information Systems And Technology',
  'Information Technology',
  'Information Technology ',
  'Information Theory',
  'Information Theory',
  'Information Theory',
  'Information Theory',
  'Infrared Astronomy',
  'Infrastructure',
  'Inorganic Chemistry',
  'Institutional Economics',
  'Instrumentation Engineering',
  'Integral Geometry',
  'Integral Geometry',
  'Integrated Library System',
  'Intellectual History',
  'Intelligence',
  'Intelligence Agency',
  'Interaction Design',
  'Interactionism',
  'Intercultural Communication',
  'Interdisciplinary Studies',
  'Interior Architecture',
  'Interior Design',
  'Interior Design (Interior Architecture)',
  'Interlibrary Loan',
  'Interlinguistics',
  'Intermodal Transportation Studies',
  'Internal Medicine',
  'International Affairs',
  'International Economics',
  'International Law',
  'International Organizations',
  'International Relations',
  'International Trade',
  'Internet ',
  'Internet Software Development',
  'Internet Sociology',
  'Internet, World Wide Web',
  'Interpretive Sociology',
  'Intersex',
  'Interstellar Medium',
  'Intuitionistic Logic',
  'Intuitionistic Logic',
  'Inventory Theory',
  'Investment Policy',
  'Iranian History',
  'Iranian Studies',
  'Irregular Warfare',
  'Irreligion',
  'Islam ',
  'Islamic Economics',
  'Islamic Law',
  'Isotope Analysis',
  'Italian History',
  'Jainism',
  'Japanese History',
  'Japanology (Japanese Studies)',
  'Jazz Studies ',
  'Jealousy Sociology',
  'Jewish Law ',
  'Journalism ',
  'Journalism, Media Studies And Communication',
  'Judaism ',
  'Jurisprudence (Philosophy Of Law)',
  'Justification',
  'K-Theory',
  'Kinematics',
  'Kinesiology / Exercise Physiology / Performance Science',
  'Kinesiology / Exercise Physiology / Performance Science',
  'Kinetics',
  'Kinship',
  'Knowledge Economy',
  'Knowledge Engineering',
  'Knowledge Management',
  'Knowledge Management',
  'Knowledge Policy',
  'Korean History',
  'Korean Studies',
  'Lti System Theory',
  'Labor Economics',
  'Labor Economics',
  'Labor History',
  'Labor Law',
  'Lagrangian Mechanics',
  'Land',
  'Land Management',
  'Landscape Archaeology And Landscape History',
  'Landscape Architecture',
  'Landscape Architecture (Landscape Planning)',
  'Landscape Design',
  'Landscape Ecology',
  'Landscape Ecology',
  'Langevin Dynamics',
  'Language Education',
  'Language Policy',
  'Languages',
  'Laser Physics',
  'Latin',
  'Latin American History',
  'Latin American Studies',
  'Lattice Theory (Order Theory)',
  'Law',
  'Law And Economics',
  'Law Enforcement',
  'Law Enforcement ',
  'Laws Of War',
  'Leadership',
  'Legal Anthropology',
  'Legal Education',
  'Legal Management',
  'Legal Psychology',
  'Leisure Studies',
  'Leisure Studies',
  'Lexicology',
  'Libertarianism ',
  'Library',
  'Library And Museum Studies',
  'Library Binding',
  'Library Circulation',
  'Library Classification',
  'Library Instruction',
  'Library Portal',
  'Library Technical Services',
  'Limited War',
  'Limnology',
  'Limnology',
  'Linear Algebra (Vector Space)',
  'Linear Programming',
  'Linguistic Anthropology',
  'Linguistic Typology',
  'Linguistics And Languages',
  'Linnaean Taxonomy',
  'Literary Criticism',
  'Literary Genre',
  'Literary Journalism',
  'Literary Journalism',
  'Literary Theory',
  'Literature',
  'Liturgy',
  'Live Action',
  'Living Systems Theory',
  'Logic',
  'Logic ',
  'Logic And Foundations Of Mathematics',
  'Logic In Computer Science',
  'Logic Programming',
  'Logic Programming',
  'Logical Reasoning',
  'Logistics',
  'Logistics',
  'Machine Learning',
  'Macroeconomics',
  'Macrosociology',
  'Magazine',
  'Magnetism',
  'Magnetohydrodynamics',
  'Magnetospheres',
  'Malacology',
  'Mammalogy',
  'Management',
  'Management',
  'Management ',
  'Management Cybernetics',
  'Management Information Systems',
  'Managerial Economics',
  'Maneuver',
  'Manufacturing Engineering',
  'Manuscriptology',
  'Marine Biology',
  'Marine Chemistry',
  'Marine Engineering',
  'Marine Transportation',
  'Maritime Archaeology',
  'Market Economy',
  'Marketing ',
  'Marketing ',
  'Marxian Economics',
  'Marxism',
  'Marxist Sociology',
  'Masculinity',
  'Masculism',
  'Mass Communication',
  'Mass Deacidification',
  'Mass Transfer',
  'Mass Transit',
  'Mastery Learning',
  'Materials Engineering',
  'Materials Physics',
  'Materials Science And Engineering',
  'Materiel',
  'Mathematical Biology',
  'Mathematical Chemistry',
  'Mathematical Economics',
  'Mathematical Logic',
  'Mathematical Logic',
  'Mathematical Optimization',
  'Mathematical Physics',
  'Mathematical Physics',
  'Mathematical Psychology',
  'Mathematical Sociology',
  'Mathematical Statistics',
  'Mathematical Statistics',
  'Mathematical System Theory',
  'Mathematics',
  'Mathematics Education',
  'Matrix Mechanics',
  'Mayan History',
  'Measure Theory',
  'Mechanical Engineering',
  'Mechanics',
  'Mechanochemistry',
  'Mechatronics',
  'Mechatronics',
  'Media Archaeology',
  'Media Psychology',
  'Media Studies (Mass Media)',
  'Medical Anthropology',
  'Medical Cybernetics',
  'Medical Education',
  'Medical Physics',
  'Medical Psychology',
  'Medical Social Work',
  'Medical Sociology',
  'Medical Toxicology',
  'Medicinal Chemistry',
  'Medicine',
  'Medieval',
  'Medieval Archaeology',
  'Medieval Literature',
  'Medieval Philosophy',
  'Men In Feminism',
  "Men'S Liberation Movement",
  "Men'S Movement",
  "Men'S Rights Movement",
  "Men'S Studies",
  'Mental Health',
  'Mercantile Law',
  'Mercenary',
  'Mesosociology',
  'Meta-Ethics',
  'Meta-Philosophy',
  'Metaphysics ',
  'Meteorology ',
  'Mexican History',
  'Micro-G Environment Research',
  'Microbiology',
  'Microbotics',
  'Microeconomics',
  'Microsociology',
  'Microwave Astronomy',
  'Middle East Studies',
  'Military Campaign',
  'Military Education And Training',
  'Military Engineering',
  'Military Exercises',
  'Military Geography',
  'Military History',
  'Military Intelligence',
  'Military Law',
  'Military Medicine',
  'Military Operation',
  'Military Operation',
  'Military Policy',
  'Military Psychology',
  'Military Science ',
  'Military Sciences',
  'Military Simulation',
  'Military Sociology',
  'Military Sports',
  'Military Weapons',
  'Mineral Physics',
  'Mineralogy',
  'Mining Engineering',
  'Misandry',
  'Misogyny',
  'Missiology',
  'Missiology',
  'Mississippian Culture',
  'Mock Combat',
  'Modal Logic',
  'Modal Logic',
  'Modal Logic',
  'Model Theory',
  'Model Theory',
  'Modern',
  'Modern Archaeology',
  'Modern History',
  'Modern Language',
  'Modern Philosophy',
  'Molecular Anthropology',
  'Molecular Biology',
  'Molecular Biology',
  'Molecular Dynamics',
  'Molecular Engineering',
  'Molecular Genetics',
  'Molecular Genetics',
  'Molecular Mechanics',
  'Molecular Mechanics',
  'Molecular Pathology',
  'Molecular Physics',
  'Molecular Virology',
  'Monetary Economics',
  'Monetary Policy',
  'Mongolian History',
  'Moral Psychology And Descriptive Ethics',
  'Moral Psychology, Descriptive Ethics, Value Theory',
  'Moral Theology',
  'Morale',
  'Morphology',
  'Multi-Valued Logic',
  'Multilinear Algebra',
  'Multimedia, Hypermedia',
  'Multivariate Analysis',
  'Museology',
  'Museum Administration',
  'Museum Education',
  'Music ',
  'Music Archaeology',
  'Music Education',
  'Music Education',
  'Music Genre',
  'Music History',
  'Music Psychology',
  'Music Theory',
  'Music Therapy',
  'Musical Composition',
  'Musical Theatre',
  'Musicology',
  'Mycology',
  'Myrmecology ',
  'Mysticism',
  'Mythology',
  'Mythology And Folklore',
  'Nanoengineering',
  'Nanomaterials',
  'Nanotechnology',
  'Nanotechnology',
  'Narratology',
  'Nationalism Studies',
  'Native American Religions',
  'Natural Language Processing',
  'Natural Language Processing (Computational Linguistics)',
  'Natural Product Chemistry',
  'Natural Resource Management',
  'Natural Resource Sociology',
  'Natural Sciences',
  'Naval',
  'Naval Architecture',
  'Naval Engineering',
  'Naval Science',
  'Naval Tactics',
  'Naval Tactics',
  'Navigation',
  'Navigation',
  'Near Eastern Archaeology',
  'Nematology',
  'Nephrology',
  'Network Science',
  'Network-Centric Warfare',
  'Neuro-Ophthalmology',
  'Neuroanthropology',
  'Neurochemistry',
  'Neuroeconomics',
  'Neuroethology',
  'Neurology',
  'Neurophysics',
  'Neurophysics',
  'Neuropsychology',
  'Neuroscience ',
  'Neuroscience In Space',
  'Neurosurgery',
  'Neurosurgery',
  'Neutrino Astronomy',
  'New Testament Greek',
  'New Cybernetics',
  'New Media Journalism',
  'New Religious Movements',
  'Newspaper',
  'Newtonian Dynamics',
  'Nigerian History',
  'Non-Euclidean Geometry',
  'Non-Fiction Writing',
  'Non-Governmental Organization (Ngo) Administration',
  'Non-Governmental Organization (Ngo) Administration',
  'Non-Standard Analysis',
  'Noncommutative Geometry',
  'Nonprofit Administration',
  'Nonprofit Administration',
  'Nontheism',
  'Nonverbal Communication',
  'Normative Ethics',
  'North American History',
  'Norwegian History',
  'Nuclear',
  'Nuclear Chemistry',
  'Nuclear Energy Policy',
  'Nuclear Engineering',
  'Nuclear Physics',
  'Number Theory',
  'Numerical Analysis',
  'Numerical Analysis',
  'Numerical Simulations',
  'Nursing',
  'Nursing Education',
  'Nutrition ',
  'Nutrition ',
  'Nutrition ',
  'Nutritional Anthropology',
  'Object Conservation',
  'Object Database',
  'Object-Oriented Programming',
  'Observational Astronomy',
  'Obstetrics ',
  'Occult',
  'Occupational Health Psychology',
  'Occupational Psychology',
  'Occupational Therapy',
  'Ocean Engineering',
  'Oceanography',
  'Oceanography',
  'Oenology',
  'Offensive',
  'Old Church Slavonic',
  'Oncology',
  'Ontology',
  'Oology',
  'Oomoto',
  'Operating Systems',
  'Operations Management',
  'Operations Research',
  'Operations Research',
  'Operations Research',
  'Operator Theory',
  'Ophthalmology',
  'Optical Astronomy',
  'Optical Engineering',
  'Optics',
  'Optimal Maintenance',
  'Optomechanics',
  'Optometry',
  'Oral And Maxillofacial Surgery',
  'Oral Literature',
  'Orbital Mechanics',
  'Orchestral Conducting',
  'Orchestral Studies',
  'Ordinary Differential Equations',
  'Organ And Historical Keyboards',
  'Organic Chemistry ',
  'Organization',
  'Organization Theory',
  'Organizational Behavior',
  'Organizational Communication',
  'Organizational Psychology',
  'Organizational Studies',
  'Organizational Studies',
  'Organizational Studies',
  'Organology',
  'Organometallic Chemistry',
  'Ornithology ',
  'Orthodontics',
  'Orthopedic Surgery',
  'Orthoptics',
  'Osteology',
  'Osteopathy',
  'Other Military',
  'Other Religions',
  'Otolaryngology',
  'Outdoor Activity',
  'Outdoor Education',
  'Outline Of Video Games',
  'P-Adic Analysis',
  'Pacific Studies',
  'Painting ',
  'Pakistan Studies',
  'Palaeoarchaeology',
  'Palaeoclimatology',
  'Palaeogeography',
  'Palatability',
  'Paleoanthropology',
  'Paleoanthropology',
  'Paleobiology',
  'Paleobiology',
  'Paleoecology',
  'Paleoethnobotany',
  'Paleontology',
  'Paleontology',
  'Paleopathology',
  'Paleoradiology',
  'Palynology',
  'Pan-American History',
  'Paralegal Studies',
  'Parallel Algorithms',
  'Parallel Computing',
  'Paramilitary',
  'Parapsychology ',
  'Parasitology',
  'Parasitology',
  'Partial Differential Equations',
  'Participatory Economics',
  'Particle Mechanics',
  'Particle Physics',
  'Pastoral Counseling',
  'Pastoral Theology',
  'Pathology',
  'Pathology',
  'Peace And Conflict Studies',
  'Peace And Conflict Studies',
  'Peace Education',
  'Pediatric Psychology',
  'Pediatrics',
  'Pedology',
  'Pedology',
  'Pedology (Children Study)',
  'Perceptual Control Theory',
  'Performance Poetry',
  'Performing Arts',
  'Periodontics',
  'Personal Fitness Training',
  'Personal Trainer / Personal Fitness Training',
  'Personality Psychology',
  'Peruvian History',
  'Pest Control',
  'Petrochemistry',
  'Petroleum Engineering',
  'Petrology',
  'Petrophysics',
  'Pharmaceutical Policy',
  'Pharmaceutical Sciences',
  'Pharmacognosy',
  'Pharmacology',
  'Pharmacy',
  'Phenomenological Sociology',
  'Phenomenology',
  'Phenomenology',
  'Philippine History',
  'Philology',
  'Philosophical Logic',
  'Philosophical Logic',
  'Philosophical Traditions And Schools',
  'Philosophy',
  'Philosophy Of Action',
  'Philosophy Of Artificial Intelligence',
  'Philosophy Of Biology',
  'Philosophy Of Chemistry',
  'Philosophy Of Economics',
  'Philosophy Of Education',
  'Philosophy Of Engineering',
  'Philosophy Of History',
  'Philosophy Of Language',
  'Philosophy Of Law',
  'Philosophy Of Mathematics',
  'Philosophy Of Mind',
  'Philosophy Of Music',
  'Philosophy Of Pain',
  'Philosophy Of Perception',
  'Philosophy Of Physics',
  'Philosophy Of Psychology',
  'Philosophy Of Religion',
  'Philosophy Of Science',
  'Philosophy Of Social Science',
  'Philosophy Of Space And Time',
  'Philosophy Of War',
  'Phonetics',
  'Phonology',
  'Photochemistry',
  'Photography ',
  'Photometry',
  'Photonics',
  'Photonics',
  'Photonics',
  'Phycology',
  'Physical Activity',
  'Physical Chemistry',
  'Physical Chemistry',
  'Physical Cosmology',
  'Physical Education / Pedagogy',
  'Physical Education/Sports Coaching',
  'Physical Fitness',
  'Physical Fitness',
  'Physical Geography',
  'Physical Metallurgy',
  'Physical Optics',
  'Physical Organic Chemistry',
  'Physical Therapy',
  'Physics',
  'Physics Education',
  'Physiology',
  'Physiotherapy',
  'Phytochemistry',
  'Phytopathology',
  'Piano',
  'Planetary Formation',
  'Planetary Geology',
  'Planetary Rings',
  'Planetary Science (Alternatively, A Part Of Earth Science)',
  'Planetary Science (Alternatively, A Part Of Space Science)',
  'Planetary Surfaces',
  'Planktology',
  'Plant Science ',
  'Plasma Physics',
  'Plastic Surgery',
  'Platonism',
  'Playwrighting',
  'Podiatry',
  'Poetics',
  'Poetry',
  'Poetry',
  'Police Science',
  'Police Science',
  'Policy Analysis',
  'Policy Sociology',
  'Policy Studies',
  'Policy Studies',
  'Polish History',
  'Polish Sociology',
  'Political Anthropology',
  'Political Behavior',
  'Political Culture',
  'Political Economic Anthropology',
  'Political Economy',
  'Political Economy',
  'Political Geography & Geopolitics',
  'Political History',
  'Political History',
  'Political Philosophy',
  'Political Psychology',
  'Political Science',
  'Political Sociology',
  'Polymer Chemistry',
  'Polymer Engineering',
  'Polymer Engineering',
  'Polymer Physics',
  'Polymer Science',
  'Pomology',
  'Popular Culture Studies',
  'Population Biology',
  'Population Genetics',
  'Population Genetics',
  'Population Geography',
  'Port Management',
  'Portuguese History',
  'Positive Psychology',
  'Post-Colonial Literature',
  'Post-Medieval Archaeology',
  'Post-Modern Literature',
  'Post-Processualism',
  'Postfeminism',
  'Postgenderism',
  'Power Engineering',
  'Pragmatics',
  'Pre-Columbian Era',
  'Prehistoric',
  'Prehistoric Archaeology',
  'Preservation',
  'Preventive Medicine',
  'Primary Care',
  'Primatology',
  'Primatology',
  'Principles Of War',
  'Print Journalism',
  'Private Defense Agency',
  'Private Military Company',
  'Probability ',
  'Probability Theory',
  'Problem Solving',
  'Procedural Law',
  'Process Design',
  'Process Engineering',
  'Processualism',
  'Professions And Applied Sciences',
  'Program Semantics',
  'Programming Language Semantics',
  'Programming Languages',
  'Programming Paradigms',
  'Project Management',
  'Projective Geometry',
  'Proof Theory',
  'Proof Theory',
  'Propaganda',
  'Property Law',
  'Prospect Research',
  'Prosthodontics',
  'Protohistoric Archaeology',
  'Proxy War',
  'Psephology',
  'Psychiatry ',
  'Psychoanalysis',
  'Psychoanalytic Sociology',
  'Psychobiology',
  'Psychobiology',
  'Psycholinguistics',
  'Psychological',
  'Psychological Anthropology',
  'Psychology',
  'Psychology ',
  'Psychology Of Religion',
  'Psychometrics',
  'Psychopathology',
  'Psychophysics',
  'Psychosomatic',
  'Psychotherapy',
  'Public Administration',
  'Public Administration',
  'Public Administration',
  'Public Anthropology',
  'Public Economics',
  'Public Finance',
  'Public Health',
  'Public History',
  'Public International Law',
  'Public Policy',
  'Public Policy',
  'Public Policy By Country',
  'Public Policy Doctrine',
  'Public Policy School',
  'Public Relations ',
  'Public Safety',
  'Public Service',
  'Public Sociology',
  'Public Speaking',
  'Pulmonology',
  'Pulmonology',
  'Puppetry',
  'Purchasing',
  'Pure Mathematics',
  'Pure Sociology',
  'Purification',
  'Quality Control',
  'Quality Control',
  'Quantitative Psychology',
  'Quantum Acoustics',
  'Quantum Biology',
  'Quantum Chemistry',
  'Quantum Chromodynamics',
  'Quantum Computing',
  'Quantum Computing',
  'Quantum Electrodynamics',
  'Quantum Field Theory',
  'Quantum Field Theory',
  'Quantum Gravity',
  'Quantum Gravity',
  'Quantum Information',
  'Quantum Mechanics',
  'Quantum Mechanics',
  'Quantum Optics',
  'Quantum Physics',
  'Quantum Statistical Mechanics',
  'Quantum Technology',
  'Queer Studies/Queer Theory',
  'Radio ',
  'Radio Astronomy',
  'Radiocarbon Dating',
  'Radiochemistry',
  'Radiology',
  'Radiophysics',
  'Randomized Algorithms',
  'Ranks',
  'Reaction Engineering',
  "Readers' Advisory",
  'Reading Education',
  'Real Analysis',
  'Real Estate Economics',
  'Real Options Analysis',
  'Reasoning Errors',
  'Recording',
  'Records Management',
  'Recreation Ecology',
  'Recreation Therapy',
  'Recursion Theory',
  'Recursion Theory',
  'Reference',
  'Reference Desk',
  'Reference Management Software',
  'Regional Geography',
  'Registrar',
  'Regression ',
  'Regulation',
  'Rehabilitation Medicine',
  'Rehabilitation Psychology',
  'Relational Database',
  'Relativistic Astrophysics',
  'Relativistic Dynamics',
  'Relativistic Kinematics',
  'Relativistic Mechanics',
  'Relativistic Quantum Mechanics',
  'Relativity',
  'Reliability Theory',
  'Religion',
  'Religious Education',
  'Religious Education Techniques',
  'Religious War',
  'Remote Sensing',
  'Remote Sensing',
  'Renewable Energy Policy',
  'Representation Theory',
  'Research Methods',
  'Resource Economics',
  'Respiratory Medicine',
  'Respiratory Therapy',
  'Response Surface Methodology',
  'Rhetoric',
  'Rhetoric',
  'Rheumatology',
  'Ring Theory',
  'Risk Management And Insurance',
  'Robotic Spacecraft',
  'Robotics',
  'Robotics ',
  'Robotics ',
  'Russian And Eastern European Studies',
  'Russian Archaeology',
  'Russian History',
  'Sacramental Theology',
  'Sacred Music',
  'Sample Survey',
  'Sampling Theory',
  'Scandinavian History',
  'Scandinavian Studies',
  'Scenography',
  'Scheduling',
  'Scholasticism',
  'School Psychology',
  'School Social Work',
  'Science Education',
  'Science Policy',
  'Science Studies/Science And Technology Studies',
  'Scientific Classification',
  'Scientific Computing (Computational Science)',
  'Scientific History',
  'Scientific Visualization',
  'Scoutcraft',
  'Screenwriting',
  'Scriptural Study And Languages',
  'Sculpture ',
  'Sea',
  'Seafaring',
  'Second-Order Cybernetics',
  'Secondary Education',
  'Security',
  'Security Classification',
  'Security Policy',
  'Sedimentology',
  'Semantics',
  'Semiconductors',
  'Semiconductors',
  'Semiotic Anthropology',
  'Semiotics ',
  'Set Theory',
  'Set Theory',
  'Settlement Archaeology',
  'Sex And Gender Distinction',
  'Sex Differences In Psychology',
  'Sex Education',
  'Sex Education',
  'Sexism',
  'Sexology',
  'Sexology',
  'Sexology',
  'Shinto',
  'Siege',
  'Sikhism ',
  'Silviculture',
  'Simulation',
  'Sindhology',
  'Singing',
  'Sinology ',
  'Slavic Studies',
  'Sleep Medicine',
  'Slow Fire',
  'Small Solar System Bodies',
  'Social Anthropology',
  'Social Capital',
  'Social Change',
  'Social Choice Theory',
  'Social Choice Theory',
  'Social Conflict Theory',
  'Social Constructionism',
  'Social Control',
  'Social Development',
  'Social Dynamics',
  'Social Economy',
  'Social Engineering',
  'Social Geography',
  'Social Movements',
  'Social Network Analysis',
  'Social Phenomenon',
  'Social Philosophy',
  'Social Philosophy And Political Philosophy',
  'Social Physics',
  'Social Policy',
  'Social Policy',
  'Social Policy',
  'Social Psychology',
  'Social Psychology',
  'Social Research',
  'Social Stratification',
  'Social Theory',
  'Social Transformation',
  'Social Work',
  'Socialist Economics',
  'Sociobiology',
  'Sociobiology',
  'Sociocybernetics',
  'Sociocybernetics',
  'Socioeconomics',
  'Sociolinguistics',
  'Sociolinguistics',
  'Sociolinguistics',
  'Sociological Theory',
  'Sociology',
  'Sociology Of Aging',
  'Sociology Of Agriculture',
  'Sociology Of Art',
  'Sociology Of Autism',
  'Sociology Of Childhood',
  'Sociology Of Conflict',
  'Sociology Of Culture',
  'Sociology Of Cyberspace',
  'Sociology Of Development',
  'Sociology Of Deviance',
  'Sociology Of Disaster',
  'Sociology Of Education',
  'Sociology Of Education',
  'Sociology Of Emotions',
  'Sociology Of Fatherhood',
  'Sociology Of Film',
  'Sociology Of Finance',
  'Sociology Of Food',
  'Sociology Of Gender',
  'Sociology Of Generations',
  'Sociology Of Globalization',
  'Sociology Of Government',
  'Sociology Of Health And Illness',
  'Sociology Of Human Consciousness',
  'Sociology Of Immigration',
  'Sociology Of Knowledge',
  'Sociology Of Language',
  'Sociology Of Law',
  'Sociology Of Leisure',
  'Sociology Of Literature',
  'Sociology Of Markets',
  'Sociology Of Marriage',
  'Sociology Of Motherhood',
  'Sociology Of Music',
  'Sociology Of Natural Resources',
  'Sociology Of Organizations',
  'Sociology Of Peace, War, And Social Conflict',
  'Sociology Of Punishment',
  'Sociology Of Race And Ethnic Relations',
  'Sociology Of Religion',
  'Sociology Of Risk',
  'Sociology Of Science',
  'Sociology Of Scientific Knowledge',
  'Sociology Of Social Change',
  'Sociology Of Social Movements',
  'Sociology Of Space',
  'Sociology Of Sport',
  'Sociology Of Sport',
  'Sociology Of Technology',
  'Sociology Of Terrorism',
  'Sociology Of The Internet',
  'Sociology Of The Body',
  'Sociology Of The Family',
  'Sociology Of The History Of Science',
  'Sociology Of Work',
  'Sociomusicology',
  'Sociotechnical Systems Theory',
  'Software Engineering',
  'Soil Chemistry',
  'Soil Mechanics',
  'Soil Physics',
  'Soil Science',
  'Solar Astronomy',
  'Solar Physics',
  'Solid Geometry',
  'Solid Mechanics',
  'Solid State Physics',
  'Solid-State Chemistry',
  'Sonochemistry',
  'Sound And Music Computing',
  'South African History',
  'South American History',
  'Southeast Asian Studies',
  'Space',
  'Space Archaeology',
  'Space Architecture',
  'Space Colonization',
  'Space Commercialization',
  'Space Corrosion',
  'Space Environment',
  'Space Exploration',
  'Space Food',
  'Space Industry',
  'Space Law',
  'Space Logistics',
  'Space Manufacturing',
  'Space Medicine',
  'Space Nuclear Power',
  'Space Plasma Physics',
  'Space Policy',
  'Space Religion',
  'Space Sciences',
  'Space Sex',
  'Space Survival',
  'Space Technology',
  'Space Telescopes',
  'Space Tourism',
  'Space Warfare',
  'Space Writing',
  'Space-Based Economy',
  'Space-Based Radar',
  'Space-Based Solar Power',
  'Spacecraft Design',
  'Spacecraft Propulsion',
  'Spanish History',
  'Special Education',
  'Special Forces',
  'Special Library',
  'Special Operations',
  'Special Relativity',
  'Specialty Foods',
  'Spectroscopy',
  'Speech And Language Pathology',
  'Speech Communication',
  'Speleology',
  'Spintronics',
  'Spirituality',
  'Spoken Word',
  'Sport Management',
  'Sport Psychology',
  'Sport Psychology',
  'Sports / Exercise',
  'Sports Coaching',
  'Sports Journalism / Sportscasting',
  'Sports Journalism / Sportscasting',
  'Sports Medicine',
  'Sports Medicine',
  'Staff',
  'Stage Design',
  'Standard English',
  'Star Formation',
  'Statics',
  'Statistical Classification',
  'Statistical Mechanics',
  'Statistical Mechanics',
  'Statistical Modelling',
  'Statistical Physics',
  'Statistical Theory',
  'Statistics',
  'Statistics',
  'Steganography',
  'Stellar Astronomy',
  'Stellar Astrophysics',
  'Stellar Dynamics',
  'Stellar Evolution',
  'Stellar Nucleosynthesis',
  'Stem Cell Research Policy',
  'Sterilization (Microbiology)',
  'Stochastic Process',
  'Stochastic Processes',
  'Storytelling',
  'Strategic Geography',
  'Strategic Studies',
  'Strategy',
  'Strategy',
  'String Theory',
  'Strings, Harp, Oud, And Guitar ',
  'Structural Biology',
  'Structural Engineering',
  'Structural Equation Model',
  'Structural Mechanics',
  'Structural Sociology',
  'Submillimetre Astronomy',
  'Substantive Law',
  'Sumerian Religion',
  'Supply Chain Management',
  'Support Vector Machine',
  'Supramolecular Chemistry',
  'Supranational Law',
  'Surface Chemistry',
  'Surface Physics',
  'Surgery',
  'Surgical Pathology',
  'Surgical Strike',
  'Survey Methodology',
  'Surveying',
  'Survival Skills',
  'Sustainability Studies',
  'Sustainable Development',
  'Swedish History',
  'Symbolic Anthropology',
  'Symbolic Interactionism',
  'Synchronic Linguistics (Or Descriptive Linguistics)',
  'Syntax',
  'Synthetic Biology',
  'Synthetic Chemistry',
  'System Dynamics',
  'System Dynamics',
  'Systematic Musicology',
  'Systematic Theology',
  'Systematics',
  'Systemic Therapy',
  'Systems Analysis',
  'Systems Analysis',
  'Systems Biology',
  'Systems Biology',
  'Systems Chemistry',
  'Systems Chemistry',
  'Systems Ecology',
  'Systems Engineering',
  'Systems Immunology',
  'Systems Neuroscience',
  'Systems Philosophy',
  'Systems Psychology',
  'Systems Science',
  'Systems Science',
  'Systems Theory',
  'Systems Theory In Anthropology',
  'Tactical Objective',
  'Tactics',
  'Taphonomy',
  'Tax Law',
  'Tax Policy',
  'Taxonomic Classification',
  'Taxonomy',
  'Technical Drawing',
  'Technical Writing',
  'Technological History',
  'Technology Management',
  'Technology And Equipment',
  'Technology Education',
  'Technology Policy',
  'Tectonics',
  'Telecommunications Engineering',
  'Teleology',
  'Television ',
  'Television ',
  'Television Studies',
  'Television Studies',
  'Tenrikyo',
  'Teratology',
  'Terminology Science',
  'Textile Design',
  'Textiles',
  'The Arts',
  'Theater (Warfare)',
  'Theatre ',
  'Theft',
  'Theism',
  'Theology ',
  'Theoretical Astronomy',
  'Theoretical Biology',
  'Theoretical Chemistry',
  'Theoretical Computer Science',
  'Theoretical Physics',
  'Theoretical Sociology',
  'Theory Of Computation',
  'Theory Of Computation',
  'Therapy',
  'Thermal Engineering',
  'Thermal Physics',
  'Thermochemistry',
  'Thermodynamics',
  'Thermodynamics',
  'Thermodynamics',
  'Third Gender',
  'Time Geography',
  'Time Series',
  'Topos Theory',
  'Tort Law ',
  'Total War',
  'Tourism Geography',
  'Toxicology',
  'Toxicology',
  'Toy And Amusement Design',
  'Toy And Amusement Design',
  'Traditional Food',
  'Traditional Medicine',
  'Traffic Psychology',
  'Transgender',
  'Translation',
  'Transpersonal Anthropology',
  'Transpersonal Psychology',
  'Transport Economics',
  'Transport Phenomena',
  'Transportation',
  'Transportation Engineering',
  'Trauma Surgery',
  'Traumatology',
  'Travel',
  'Travel Psychology',
  'Trench Warfare',
  'Trigonometry',
  'Turkish History',
  'Type Design',
  'Type Theory',
  'Type Theory',
  'Uv Astronomy',
  'Ubiquitous Computing',
  'Unconventional',
  'Undercover',
  'Universal Algebra',
  'Urban Anthropology',
  'Urban Archaeology',
  'Urban Geography',
  'Urban Planning (Urban Design)',
  'Urban Studies Or Urban Sociology/Rural Sociology',
  'Urology',
  'Usage',
  'User Experience Design',
  'User Experience Evaluation',
  'User Interface Design',
  'Vlsi Design',
  'Vaccination Policy',
  'Vedic Study',
  'Vehicle Dynamics',
  'Vehicles',
  'Venezuelan History',
  'Veterinary Medicine',
  'Victimology',
  'Virology',
  'Virtue Ethics',
  'Visual Anthropology',
  'Visual Arts',
  'Visual Communication',
  'Visual Sociology',
  'Viticulture',
  'Vocational Education',
  'Volcanology',
  'War ',
  'War Crimes',
  'Warrior',
  'Waste Management',
  'Welfare Economics',
  'White Studies',
  'Wildlife Management',
  'Wildlife Observation',
  'Wind Ensemble Conducting',
  'Wireless Computing (Mobile Computing)',
  "Women'S Rights",
  "Women'S Studies",
  'Woodcraft',
  'Woodwinds, Brass, And Percussion',
  'Word Usage',
  'World Englishes',
  'World History',
  'World Literature',
  'World-Systems Theory',
  'X-Ray Astronomy',
  'Xenobiology',
  'Zooarchaeology',
  'Zoology ',
  'Zoosemiotics',
  'Zootomy',
  'Zoroastrianism'
];
