export let majorsAndMinors = [
  'Anthropology',
  'Anthropological criminology',
  'Anthropological linguistics',
  'Synchronic linguistics (or Descriptive linguistics)',
  'Diachronic linguistics (or Historical linguistics)',
  'Ethnolinguistics',
  'Semiotic anthropology',
  'Sociolinguistics',
  'Anthrozoology',
  'Biological anthropology',
  'Gene-culture coevolution',
  'Evolutionary anthropology',
  'Forensic anthropology',
  'Human behavioral ecology',
  'Human evolution',
  'Medical anthropology',
  'Molecular anthropology',
  'Neuroanthropology',
  'Nutritional anthropology',
  'Paleoanthropology',
  'Population genetics',
  'Primatology',
  'Biocultural anthropology',
  'Cultural anthropology',
  'Anthropology of development',
  'Anthropology of religion',
  'Applied anthropology',
  'Cognitive anthropology',
  'Cyborg anthropology',
  'Digital anthropology',
  'Digital culture',
  'Ecological anthropology',
  'Economic anthropology',
  'Environmental anthropology',
  'Ethnobiology',
  'Ethnobotany',
  'Ethnography',
  'Ethnohistory',
  'Ethnology',
  'Ethnomuseology',
  'Ethnomusicology',
  'Feminist anthropology',
  'Folklore',
  'Kinship',
  'Legal anthropology',
  'Mythology',
  'Missiology',
  'Political anthropology',
  'Political economic anthropology',
  'Psychological anthropology',
  'Public anthropology',
  'Symbolic anthropology',
  'Transpersonal anthropology',
  'Urban anthropology',
  'Linguistic anthropology',
  'Social anthropology',
  'Anthropology of art',
  'Anthropology of institutions',
  'Anthropology of media',
  'Visual anthropology',
  'Archaeology',
  'Aerial archaeology',
  'Aviation archaeology',
  'Anthracology',
  'Archaeo-optics',
  'Archaeoacoustics',
  'Archaeoastronomy',
  'Archaeogeography',
  'Archaeological culture',
  'Archaeological theory',
  'Great ages archaeology',
  'Functionalism',
  'Processualism',
  'Post-processualism',
  'Cognitive archaeology',
  'Gender archaeology',
  'Feminist archaeology',
  'Archaeometry',
  'Archaeogenetics',
  'Bioarchaeology',
  'Computational archaeology',
  'Dendrochronology',
  'Geoarchaeology',
  'Isotope analysis',
  'Palynology',
  'Radiocarbon dating',
  'Zooarchaeology',
  'Archaeology of religion and ritual',
  'Archaeology of trade',
  'Archaeomythology',
  'Architectural analytics',
  'Battlefield archaeology',
  'Calceology',
  'Conflict archaeology',
  'Data archaeology',
  'Digital archaeology',
  'Experimental archaeology',
  'Environmental archaeology',
  'Ethnoarchaeology',
  'Forensic archaeology',
  'Glyptology',
  'History of archaeology',
  'Household archaeology',
  'Landscape archaeology and Landscape history',
  'Manuscriptology',
  'Maritime archaeology',
  'Media archaeology',
  'Modern archaeology',
  'Settlement archaeology',
  'Music archaeology',
  'Osteology',
  'Palaeoarchaeology',
  'Paleoanthropology',
  'Paleoethnobotany',
  'Paleopathology',
  'Paleoradiology',
  'Taphonomy',
  'Urban archaeology',
  'Historical archaeology',
  'Prehistoric archaeology',
  'protohistoric archaeology',
  'Biblical archaeology',
  'Classical archaeology',
  'Egyptology',
  'Assyriology',
  'Etruscology',
  'Near Eastern archaeology',
  'Medieval archaeology',
  'Post-medieval archaeology',
  'Industrial archaeology',
  'Contemporary archaeology',
  'African archaeology',
  'Australian archaeology',
  'European archaeology',
  'Russian archaeology',
  'Archaeology of the Americas',
  'Archaeology of China',
  'Archaeology of Israel',
  'History',
  'African history',
  'South African history',
  'Egyptian history',
  'Nigerian history',
  'Pan-American history',
  'North American history',
  'American history',
  'Canadian history',
  'Mexican history',
  'Cuban history',
  'South American history',
  'Latin American history',
  'Brazilian history',
  'Colombian history',
  'Venezuelan history',
  'Peruvian history',
  'Argentine history',
  'Pre-Columbian era',
  'Mayan history',
  'Aztec history',
  'Inca history',
  'Mississippian culture',
  'Ancient history',
  'Ancient Greek history ',
  'Ancient Roman history ',
  'History of the Roman Republic',
  'History of the Roman Empire',
  'Ancient Egyptian history ',
  'Ancient Chinese history ',
  'Ancient Middle Eastern history',
  'Asian history',
  'Chinese history',
  'Japanese history',
  'Korean history',
  'Mongolian history',
  'Indian history ',
  'Turkish history',
  'Iranian history',
  'Philippine history',
  'Indonesian history',
  'European history',
  'British history',
  'French history',
  'German history',
  'Dutch history',
  'Italian history',
  'Spanish history',
  'Portuguese history',
  'Polish history',
  'Balkan history',
  'Scandinavian history',
  'Swedish history',
  'Norwegian history',
  'Danish history',
  'Finnish history',
  'Icelandic history',
  'Russian history',
  'Australian history',
  'Economic history',
  'Environmental history',
  'Intellectual history',
  'Modern history',
  'Political history',
  'Scientific history',
  'Technological history',
  'World history',
  'Public history',
  'Linguistics and languages',
  'Classics ',
  'Languages',
  'Business English',
  'Classical language',
  'Modern language',
  'Standard English',
  'World Englishes',
  'Applied linguistics',
  'Computational linguistics',
  'Discourse analysis',
  'English studies',
  'Etymology',
  'Grammar',
  'Historical linguistics',
  'History of linguistics',
  'Interlinguistics',
  'Lexicology',
  'Linguistic typology',
  'Morphology',
  'Natural language processing',
  'Philology',
  'Phonetics',
  'Phonology',
  'Pragmatics',
  'Psycholinguistics',
  'Semantics',
  'Semiotics ',
  'Sociolinguistics',
  'Syntax',
  'Terminology science',
  'Composition studies',
  'Rhetoric',
  'Usage',
  'Word usage',
  'Philosophy',
  'Meta-philosophy',
  'Metaphysics ',
  'Ontology',
  'Teleology',
  'Philosophy of mind',
  'Philosophy of artificial intelligence',
  'Philosophy of perception',
  'Philosophy of pain',
  'Philosophy of space and time',
  'Philosophy of action',
  'Determinism and Free will',
  'Epistemology ',
  'Justification',
  'Reasoning errors',
  'Ethics ',
  'Meta-ethics',
  'Normative ethics',
  'Virtue ethics',
  'Applied ethics',
  'Animal rights',
  'Bioethics',
  'Environmental ethics',
  'Moral psychology, Descriptive ethics, Value theory',
  'Aesthetics ',
  'Social philosophy and Political philosophy',
  'Anarchism ',
  'Feminist philosophy',
  'Libertarianism ',
  'Marxism',
  'Philosophical traditions and schools',
  'Platonism',
  'Aristotelianism',
  'Analytic philosophy',
  'Continental philosophy',
  'Eastern philosophy',
  'Feminist philosophy',
  'History of philosophy',
  'Ancient philosophy',
  'Medieval philosophy',
  'Scholasticism',
  'Humanism ',
  'Modern philosophy',
  'Contemporary philosophy',
  'Logic ',
  'Philosophical logic',
  'Mathematical logic',
  'Applied philosophy',
  'Philosophy of education',
  'Philosophy of history',
  'Philosophy of religion',
  'Philosophy of language',
  'Philosophy of law',
  'Philosophy of mathematics',
  'Philosophy of music',
  'Philosophy of science',
  'Philosophy of social science',
  'Philosophy of physics',
  'Philosophy of biology',
  'Philosophy of chemistry',
  'Philosophy of economics',
  'Philosophy of psychology',
  'Philosophy of engineering',
  'Systems philosophy',
  'Religion',
  'Abrahamic religions',
  'Christianity ',
  'Christian theology ',
  'Islam ',
  'Judaism ',
  'Apologetics',
  'Indian religions',
  'Buddhism ',
  'Hinduism ',
  'Jainism',
  'Sikhism ',
  'East Asian religions',
  'Chinese folk religion',
  'Confucianism',
  'Shinto',
  'Daoism ',
  'I-Kuan Tao',
  'Caodaism',
  'Chondogyo',
  'Tenrikyo',
  'Oomoto',
  'Other religions',
  'African religions',
  'Ancient Egyptian religion',
  'Native American religions',
  'Gnosticism',
  'Occult',
  'Esotericism',
  'Mysticism',
  'Spirituality',
  'New religious movements',
  'Sumerian religion',
  'Zoroastrianism',
  'Comparative religion',
  'Mythology and Folklore',
  'Theism',
  'Irreligion',
  'Agnosticism',
  'Atheism ',
  'Nontheism',
  'The arts',
  'Culinary arts',
  'Acquired taste',
  'Aftertaste',
  'Appetite',
  'Artisanal food',
  'Cooking',
  'Cuisine',
  'Culinary arts',
  'Culinary tourism',
  'Delicacy',
  'Diet',
  'Flavor',
  'Food choice',
  'Food pairing',
  'Food photography',
  'Food preparation',
  'Food presentation',
  'Food safety',
  'Food security',
  'Food studies',
  'Gastronomy',
  'Gourmet',
  'Palatability',
  'Specialty foods',
  'Traditional food',
  'Literature',
  'Poetry',
  'Comparative literature',
  'English literature',
  'World literature',
  'American literature',
  'British literature',
  'History of literature',
  'Medieval literature',
  'Post-colonial literature',
  'Post-modern literature',
  'Literary theory',
  'Critical theory ',
  'Literary criticism',
  'Poetics',
  'Rhetoric',
  'Literary genre',
  'Creative writing',
  'Creative nonfiction',
  'Fiction writing ',
  'Non-fiction writing',
  'Literary journalism',
  'Poetry',
  'Screenwriting',
  'Playwrighting',
  'Performing arts',
  'Music ',
  'Accompanying',
  'Chamber music',
  'Church music',
  'Musical composition',
  'Conducting',
  'Choral conducting',
  'Orchestral conducting',
  'Wind ensemble conducting',
  'Early music',
  'Jazz studies ',
  'Music education',
  'Music history',
  'Music genre',
  'Music theory',
  'Musicology',
  'Historical musicology',
  'Systematic musicology',
  'Ethnomusicology',
  'Organology',
  'Organ and historical keyboards',
  'Piano',
  'Strings, harp, oud, and guitar ',
  'Singing',
  'Woodwinds, brass, and percussion',
  'Recording',
  'Orchestral studies',
  'Dance ',
  'Choreography',
  'Dance notation',
  'Ethnochoreology',
  'History of dance',
  'Television ',
  'Television studies',
  'Theatre ',
  'History',
  'Acting',
  'Directing',
  'Stage design',
  'Puppetry',
  'Dramaturgy',
  'Scenography',
  'Musical theatre',
  'Film ',
  'Animation',
  'Live action',
  'Filmmaking',
  'Film criticism',
  'Film genre',
  'Film studies',
  'Film theory',
  'Oral literature',
  'Public speaking',
  'Performance poetry',
  'Spoken word',
  'Storytelling',
  'Electronic game',
  'Arcade game',
  'Audio game',
  'Outline of video games',
  'Visual arts',
  'Craft',
  'Fine arts',
  'Forgery',
  'Graphic arts',
  'Drawing ',
  'Painting ',
  'Photography ',
  'Sculpture ',
  'Economics',
  'Agricultural economics',
  'Anarchist economics',
  'Applied economics',
  'Behavioural economics',
  'Bioeconomics',
  'Business',
  'Complexity economics',
  'Computational economics',
  'Consumer economics',
  'Development economics',
  'Digital economy',
  'Ecological economics',
  'Econometrics',
  'Economic geography',
  'Economic history',
  'Economic sector',
  'Economic sociology',
  'Economic systems',
  'Economic value',
  'Energy economics',
  'Entrepreneurial economics',
  'Environmental economics',
  'Evolutionary economics',
  'Experimental economics',
  'Feminist economics',
  'Financial economics',
  'Financial econometrics',
  'Green economics',
  'Growth economics',
  'Human development theory',
  'Industrial organization',
  'Information economics',
  'Institutional economics',
  'International economics',
  'Islamic economics',
  'Knowledge economy',
  'Labor economics',
  'Law and economics',
  'Macroeconomics',
  'Managerial economics',
  'Market economy',
  'Marxian economics',
  'Mathematical economics',
  'Microeconomics',
  'Monetary economics',
  'Neuroeconomics',
  'Participatory economics',
  'Political economy',
  'Public finance',
  'Public economics',
  'Real estate economics',
  'Resource economics',
  'Social choice theory',
  'Socialist economics',
  'Socioeconomics',
  'Transport economics',
  'Welfare economics',
  'Geography',
  'Cartography ',
  'Navigation',
  'Human geography',
  'Cultural geography',
  'Feminist geography',
  'Economic geography',
  'Development geography',
  'Historical geography',
  'Time geography',
  'Political geography & geopolitics',
  'Military geography',
  'Strategic geography',
  'Population geography',
  'Social geography',
  'Behavioral geography',
  "Children's geographies",
  'Health geography',
  'Tourism geography',
  'Urban geography',
  'Environmental geography',
  'Physical geography',
  'Biogeography',
  'Climatology',
  'Palaeoclimatology',
  'Coastal geography',
  'Geomorphology',
  'Geodesy',
  'Hydrology/Hydrography',
  'Glaciology',
  'Limnology',
  'Oceanography',
  'Landscape ecology',
  'Palaeogeography',
  'Regional geography',
  'Remote sensing',
  'Interdisciplinary studies',
  'Area studies',
  'African studies',
  'American studies',
  'Appalachian studies',
  'Canadian studies',
  'Latin American studies',
  'Asian studies',
  'Central Asian studies',
  'East Asian studies',
  'Indology (Indian studies)',
  'Iranian studies',
  'Japanology (Japanese studies)',
  'Korean studies',
  'Pakistan studies',
  'Sindhology',
  'Sinology ',
  'Southeast Asian studies',
  'European studies',
  'Celtic studies',
  'German studies',
  'Indo-European studies',
  'Scandinavian studies',
  'Slavic studies',
  'Australian studies',
  'Pacific studies',
  'Middle East studies',
  'Russian and Eastern European studies',
  'Ethnic and cultural studies',
  'Cultural studies',
  'Ethnic studies',
  'Ethnology',
  'Culturology',
  'Cross-cultural studies',
  'White studies',
  'Black studies',
  'Gender and sexuality studies',
  'Androcentrism',
  'Feminine psychology',
  'Feminism',
  'Feminity',
  'Feminist theory',
  'Gender dysphoria',
  'Gender history',
  'Gender identity',
  'Gender role',
  'Gender studies/Gender theory',
  'Genderqueer',
  'Gynocentrism',
  'Heterosexism',
  'Human sexual behavior',
  'Human sexuality ',
  'Intersex',
  'Masculinity',
  'Masculism',
  'Men in feminism',
  "Men's liberation movement",
  "Men's movement",
  "Men's rights movement",
  "Men's studies",
  'Misandry',
  'Misogyny',
  'Postfeminism',
  'Postgenderism',
  'Queer studies/Queer theory',
  'Sex and gender distinction',
  'Sex differences in psychology',
  'Sex education',
  'Sexism',
  'Sexology',
  'Third gender',
  'Transgender',
  "Women's rights",
  "Women's studies",
  'Organizational studies',
  'Business economics',
  'Business ethics',
  'Business studies',
  'Decision science',
  'Entrepreneurship',
  'Human resources management',
  'Industrial organization',
  'Management',
  'Organizational behavior',
  'Organization theory',
  'Project management',
  'Quality control',
  'Strategy',
  'Political science',
  'American politics',
  'Canadian politics',
  'Civics',
  'Comparative politics',
  'European studies',
  'Geopolitics (Political geography)',
  'International relations',
  'International organizations',
  'Nationalism studies',
  'Peace and conflict studies',
  'Policy studies',
  'Political behavior',
  'Political culture',
  'Political economy',
  'Political history',
  'Political philosophy',
  'Psephology',
  'Public administration',
  'Nonprofit administration',
  'Non-governmental organization (NGO) administration',
  'Public policy',
  'Social choice theory',
  'Psychology',
  'Abnormal psychology',
  'Applied psychology',
  'Asian psychology',
  'Biological psychology',
  'Black psychology',
  'Clinical psychology',
  'Clinical neuropsychology',
  'Cognitive psychology',
  'Community psychology',
  'Comparative psychology',
  'Conservation psychology',
  'Consumer psychology',
  'Counseling psychology',
  'Criminal psychology',
  'Cultural psychology',
  'Developmental psychology',
  'Differential psychology',
  'Ecological psychology',
  'Educational psychology',
  'Environmental psychology',
  'Evolutionary psychology',
  'Experimental psychology',
  'Group psychology',
  'Family psychology',
  'Feminine psychology',
  'Forensic psychology',
  'Forensic developmental psychology',
  'Health psychology',
  'Humanistic psychology',
  'Indigenous psychology',
  'Legal psychology',
  'Mathematical psychology',
  'Media psychology',
  'Medical psychology',
  'Military psychology',
  'Moral psychology and Descriptive ethics',
  'Music psychology',
  'Neuropsychology',
  'Occupational psychology',
  'Occupational health psychology',
  'Organizational psychology',
  'Parapsychology ',
  'Pediatric psychology',
  'Pedology (children study)',
  'Personality psychology',
  'Phenomenology',
  'Political psychology',
  'Positive psychology',
  'Problem solving',
  'Psychoanalysis',
  'Psychobiology',
  'Psychometrics',
  'Psychology of religion',
  'Psychopathology',
  'Child psychopathology',
  'Psychophysics',
  'Quantitative psychology',
  'Rehabilitation psychology',
  'School psychology',
  'Social psychology',
  'Sport psychology',
  'Traffic psychology',
  'Transpersonal psychology',
  'Travel psychology',
  'Sociology',
  'Analytical sociology',
  'Applied sociology',
  'Political sociology',
  'Public sociology',
  'Social engineering',
  'Leisure studies',
  'Architectural sociology',
  'Behavioral sociology',
  'Chinese sociology',
  'Collective behavior',
  'Activism',
  'Social movements',
  'Social phenomenon',
  'Community informatics',
  'Social network analysis',
  'Comparative sociology',
  'Conflict theory',
  'Critical sociology',
  'Cultural sociology',
  'Cultural studies',
  'Criminology/Criminal justice ',
  'Critical management studies',
  'Demography/Population',
  'Digital sociology',
  'Dramaturgical sociology',
  'Economic sociology',
  'Educational sociology',
  'Empirical sociology',
  'Environmental sociology',
  'Evolutionary sociology',
  'Feminist sociology',
  'Figurational sociology',
  'Futures studies ',
  'Historical sociology',
  'Human ecology',
  'Humanistic sociology',
  'Industrial sociology',
  'Interactionism',
  'Internet sociology',
  'Interpretive sociology',
  'Phenomenology',
  'Ethnomethodology',
  'Symbolic interactionism',
  'Social constructionism',
  'Jealousy sociology',
  'Macrosociology',
  'Marxist sociology',
  'Mathematical sociology',
  'Medical sociology',
  'Mesosociology',
  'Microsociology',
  'Military sociology',
  'Natural resource sociology',
  'Organizational studies',
  'Phenomenological sociology',
  'Policy sociology',
  'Polish sociology',
  'Psychoanalytic sociology',
  'Science studies/Science and technology studies',
  'Sexology',
  'Social capital',
  'Social change',
  'Social conflict theory',
  'Social control',
  'Pure sociology',
  'Social economy',
  'Social philosophy',
  'Social psychology',
  'Social policy',
  'Social research',
  'Social transformation',
  'Computational sociology',
  'Economic sociology/Socioeconomics',
  'Economic development',
  'Social development',
  'Sociology of aging',
  'Sociology of agriculture',
  'Sociology of art',
  'Sociology of autism',
  'Sociology of childhood',
  'Sociology of conflict',
  'Sociology of culture',
  'Sociology of cyberspace',
  'Sociology of deviance',
  'Sociology of development',
  'Sociology of disaster',
  'Sociology of education',
  'Sociology of emotions',
  'Sociology of fatherhood',
  'Sociology of film',
  'Sociology of finance',
  'Sociology of food',
  'Sociology of gender',
  'Sociology of generations',
  'Sociology of globalization',
  'Sociology of government',
  'Sociology of health and illness',
  'Sociology of human consciousness',
  'Sociology of immigration',
  'Sociology of knowledge',
  'Sociology of language',
  'Sociology of law',
  'Sociology of leisure',
  'Sociology of literature',
  'Sociology of markets',
  'Sociology of marriage',
  'Sociology of motherhood',
  'Sociology of music',
  'Sociology of natural resources',
  'Sociology of organizations',
  'Sociology of peace, war, and social conflict',
  'Sociology of punishment',
  'Sociology of race and ethnic relations',
  'Sociology of religion',
  'Sociology of risk',
  'Sociology of science',
  'Sociology of scientific knowledge',
  'Sociology of social change',
  'Sociology of social movements',
  'Sociology of space',
  'Sociology of sport',
  'Sociology of technology',
  'Sociology of terrorism',
  'Sociology of the body',
  'Sociology of the family',
  'Sociology of the history of science',
  'Sociology of the Internet',
  'Sociology of work',
  'Social theory',
  'Social stratification',
  'Sociological theory',
  'Sociobiology',
  'Sociocybernetics',
  'Sociolinguistics',
  'Sociomusicology',
  'Structural sociology',
  'Theoretical sociology',
  'Urban studies or Urban sociology/Rural sociology',
  'Victimology',
  'Visual sociology',
  'Natural sciences',
  'Biology',
  'Aerobiology',
  'Anatomy',
  'Comparative anatomy',
  'Human anatomy ',
  'Biochemistry ',
  'Bioinformatics',
  'Biophysics ',
  'Biotechnology ',
  'Botany ',
  'Ethnobotany',
  'Phycology',
  'Cell biology ',
  'Chronobiology',
  'Cognitive biology',
  'Computational biology',
  'Conservation biology',
  'Cryobiology',
  'Developmental biology',
  'Embryology',
  'Gerontology',
  'Teratology',
  'Ecology ',
  'Agroecology',
  'Ethnoecology',
  'Human ecology',
  'Landscape ecology',
  'Genetics ',
  'Behavioural genetics',
  'Molecular genetics',
  'Population genetics',
  'Geobiology',
  'Endocrinology',
  'Evolution ',
  'Systematics',
  'Taxonomy',
  'Histology',
  'Human biology',
  'Immunology ',
  'Limnology',
  'Linnaean taxonomy',
  'Marine biology',
  'Mathematical biology',
  'Microbiology',
  'Molecular biology',
  'Mycology',
  'Neuroscience ',
  'Behavioral neuroscience',
  'Neurophysics',
  'Computational Neuroscience',
  'Nutrition ',
  'Paleobiology',
  'Paleontology',
  'Parasitology',
  'Pathology',
  'Anatomical pathology',
  'Clinical pathology',
  'Dermatopathology',
  'Forensic pathology',
  'Hematopathology',
  'Histopathology',
  'Molecular pathology',
  'Surgical pathology',
  'Phytopathology',
  'Physiology',
  'Human physiology',
  'Exercise physiology',
  'Population biology',
  'Psychobiology',
  'Quantum biology',
  'Sociobiology',
  'Structural Biology',
  'Systems biology',
  'Theoretical biology',
  'Toxicology',
  'Virology',
  'Molecular virology',
  'Xenobiology',
  'Zoology ',
  'Animal communications',
  'Apiology',
  'Arachnology',
  'Carcinology',
  'Cetology',
  'Entomology',
  'Forensic entomology',
  'Ethnozoology',
  'Ethology',
  'Helminthology',
  'Herpetology',
  'Ichthyology ',
  'Mammalogy',
  'Malacology',
  'Conchology',
  'Myrmecology ',
  'Nematology',
  'Neuroethology',
  'Oology',
  'Ornithology ',
  'Planktology',
  'Primatology',
  'Zootomy',
  'Zoosemiotics',
  'Chemistry',
  'Agrochemistry',
  'Analytical chemistry',
  'Astrochemistry',
  'Atmospheric chemistry',
  'Biochemistry ',
  'Catalysts',
  'Chemical engineering ',
  'Chemical biology',
  'Chemical physics',
  'Cheminformatics',
  'Computational chemistry',
  'Cosmochemistry',
  'Environmental chemistry',
  'Femtochemistry',
  'Flavor',
  'Flow chemistry',
  'Geochemistry',
  'Green chemistry',
  'Histochemistry',
  'Hydrogenation',
  'Immunochemistry',
  'Inorganic chemistry',
  'Marine chemistry',
  'Mathematical chemistry',
  'Mechanochemistry',
  'Medicinal chemistry',
  'Molecular biology',
  'Molecular mechanics',
  'Nanotechnology',
  'Natural product chemistry',
  'Neurochemistry',
  'Nuclear chemistry',
  'Oenology',
  'Organic chemistry ',
  'Organometallic chemistry',
  'Petrochemistry',
  'Pharmacology',
  'Photochemistry',
  'Physical chemistry',
  'Electrochemistry',
  'Physical organic chemistry',
  'Phytochemistry',
  'Polymer chemistry',
  'Quantum chemistry',
  'Radiochemistry',
  'Soil chemistry',
  'Solid-state chemistry',
  'Sonochemistry',
  'Supramolecular chemistry',
  'Surface chemistry',
  'Synthetic chemistry',
  'Systems chemistry',
  'Theoretical chemistry',
  'Thermochemistry',
  'Earth sciences',
  'Edaphology',
  'Environmental science',
  'Environmental chemistry',
  'Gemology',
  'Geobiology',
  'Geodesy',
  'Geography ',
  'Geology ',
  'Geochemistry',
  'Geomorphology',
  'Geophysics ',
  'Glaciology',
  'Hydrogeology',
  'Hydrology ',
  'Meteorology ',
  'Mineralogy',
  'Oceanography',
  'Pedology',
  'Paleontology',
  'Paleobiology',
  'Paleoecology',
  'Petrology',
  'Planetary science (alternatively, a part of space science)',
  'Sedimentology',
  'Soil science',
  'Speleology',
  'Tectonics',
  'Volcanology',
  'Physics',
  'Acoustics ',
  'Quantum acoustics',
  'Agrophysics',
  'Applied physics ',
  'Accelerator physics',
  'Communication physics',
  'Astrophysics',
  'Atmospheric physics',
  'Atmospheric electricity',
  'Atomic, molecular, and optical physics',
  'Atomic physics',
  'Biophysics ',
  'Neurophysics',
  'Chemical physics',
  'Classical physics',
  'Computational physics',
  'Condensed matter physics',
  'Cryogenics',
  'Digital physics',
  'Dynamics',
  'Analytical dynamics',
  'Astrodynamics',
  'Brownian dynamics',
  'File dynamics',
  'Flight dynamics',
  'Fluid dynamics',
  'Aerodynamics',
  'Hydrodynamics',
  'Fractional dynamics',
  'Geodynamics',
  'Molecular dynamics',
  'Newtonian dynamics',
  'Langevin dynamics',
  'Quantum chromodynamics',
  'Quantum electrodynamics',
  'Relativistic dynamics',
  'Stellar dynamics',
  'System dynamics',
  'Thermodynamics',
  'Vehicle dynamics',
  'Econophysics',
  'Electromagnetism',
  'Electricity',
  'Electrostatic',
  'Magnetism',
  'Engineering physics',
  'Experimental physics',
  'Geophysics ',
  'Biogeophysics',
  'Geomagnetism',
  'Kinematics',
  'Fluid kinematics',
  'Relativistic kinematics',
  'Kinetics',
  'Electrokinetics',
  'Homeokinetics',
  'Laser physics',
  'Materials physics',
  'Mathematical physics',
  'Medical physics',
  'Mechanics',
  'Analytical mechanics',
  'Applied mechanics',
  'Ballistics',
  'Biomechanics',
  'Celestial mechanics',
  'Classical mechanics',
  'Continuum mechanics',
  'Fluid mechanics',
  'Compressible flow',
  'Gas mechanics',
  'Fracture mechanics',
  'Hamiltonian mechanics',
  'Hydraulics',
  'Lagrangian mechanics',
  'Matrix mechanics',
  'Molecular mechanics',
  'Optomechanics',
  'Particle mechanics',
  'Quantum mechanics',
  'Relativistic mechanics',
  'Relativistic quantum mechanics',
  'Soil mechanics',
  'Solid mechanics',
  'Statistical mechanics',
  'Quantum statistical mechanics',
  'Mineral physics',
  'Molecular physics',
  'Nuclear physics',
  'Optics',
  'Geometrical optics',
  'Physical optics',
  'Quantum optics',
  'Particle physics',
  'Petrophysics',
  'Photonics',
  'Physical chemistry',
  'Plasma physics',
  'Polymer physics',
  'Quantum physics',
  'Quantum technology',
  'Radiophysics',
  'Relativity',
  'General relativity',
  'Special relativity',
  'Social physics',
  'Soil physics',
  'Solid state physics',
  'Spintronics',
  'Statics',
  'Fluid statics',
  'Statistical physics',
  'Surface physics',
  'Theoretical physics',
  'Quantum field theory',
  'Quantum gravity',
  'Thermal physics',
  'Space sciences',
  'Aerospace engineering',
  'Aerospace architecture',
  'Aerospace physiology',
  'Aerospace manufacturing',
  'Astronautics',
  'Space architecture',
  'Space colonization',
  'Space commercialization',
  'Space-based economy',
  'Space industry',
  'Space manufacturing',
  'Space tourism',
  'Space environment',
  'Space logistics',
  'Space food',
  'Space medicine',
  'Neuroscience in space',
  'Space religion',
  'Space sex',
  'Space survival',
  'Space warfare',
  'Space writing',
  'Aeronautics',
  'Control engineering',
  'Human spaceflight',
  'Robotic spacecraft',
  'Space corrosion',
  'Space technology',
  'Space telescopes',
  'Space-based radar',
  'Space-based solar power',
  'Spacecraft design',
  'Spacecraft propulsion',
  'Asteroid-impact avoidance',
  'Astrobiology',
  'Astrobotany',
  'Astrochemistry',
  'Theoretical astronomy',
  'Cosmochemistry',
  'Cosmology',
  'Micro-g environment research',
  'Remote sensing',
  'Space archaeology',
  'Space exploration',
  'Space law',
  'Space nuclear power',
  'Astronomy',
  'Archaeoastronomy',
  'Astrometry',
  'Amateur astronomy',
  'Forensic astronomy',
  'Extragalactic astronomy',
  'Galactic astronomy',
  'High-energy astronomy',
  'Observational astronomy',
  'Radio astronomy',
  'Microwave astronomy',
  'Submillimetre astronomy',
  'Infrared astronomy',
  'Optical astronomy',
  'UV astronomy',
  'X-ray astronomy',
  'Gamma-ray astronomy',
  'Cosmic-ray astronomy',
  'Neutrino astronomy',
  'Gravitational wave astronomy',
  'Photometry',
  'Spectroscopy',
  'Stellar astronomy',
  'Solar astronomy',
  'Astrophysics',
  'Celestial mechanics',
  'Compact objects',
  'Computational astrophysics',
  'Gravitational astronomy',
  'Black holes',
  'Interstellar medium',
  'Numerical simulations',
  'Astrophysical plasma',
  'Galaxy formation and evolution',
  'High-energy astrophysics',
  'Hydrodynamics',
  'Magnetohydrodynamics',
  'Star formation',
  'Orbital mechanics',
  'Physical cosmology',
  'Relativistic astrophysics',
  'Stellar astrophysics',
  'Helioseismology',
  'Solar physics',
  'Stellar evolution',
  'Stellar nucleosynthesis',
  'Space plasma physics',
  'Planetary science (alternatively, a part of earth science)',
  'Atmospheric science',
  'Exoplanetology',
  'Planetary formation',
  'Planetary rings',
  'Magnetospheres',
  'Planetary geology',
  'Planetary surfaces',
  'Small Solar System bodies',
  'Formal sciences',
  'Computer science',
  'Theory of computation',
  'Automata theory (Formal languages)',
  'Computability theory',
  'Computational complexity theory',
  'Concurrency theory',
  'VLSI design',
  'Operating systems',
  'Algorithms',
  'Randomized algorithms',
  'Distributed algorithms',
  'Parallel algorithms',
  'Computational geometry',
  'Database',
  'Data structures',
  'Computer architecture',
  'Computer communications (networks)',
  'Information theory',
  'Internet, World Wide Web',
  'Wireless computing (Mobile computing)',
  'Ubiquitous computing',
  'Cloud computing',
  'Computer program',
  'Computer programming',
  'Computer security and reliability',
  'Cryptanalysis',
  'Cryptography',
  'Fault-tolerant computing',
  'Distributed computing',
  'Grid computing',
  'Parallel computing',
  'High-performance computing',
  'Quantum computing',
  'Computer graphics',
  'Image processing',
  'Scientific visualization',
  'Software engineering',
  'Formal methods (Formal verification)',
  'Programming languages',
  'Programming paradigms',
  'Imperative programming',
  'Object-oriented programming',
  'Functional programming',
  'Logic programming',
  'Concurrent programming',
  'Program semantics',
  'Type theory',
  'Compilers',
  'Human–computer interaction',
  'Information science ',
  'Data management',
  'Data mining',
  'Database ',
  'Relational database',
  'Distributed database',
  'Object database',
  'Information retrieval',
  'Information management',
  'Information system',
  'Information technology',
  'Knowledge management',
  'Multimedia, hypermedia',
  'Sound and music computing',
  'Quantum information',
  'Theoretical computer science',
  'Artificial intelligence ',
  'Cognitive science',
  'Automated reasoning',
  'Machine learning',
  'Artificial neural network',
  'Support vector machine',
  'Natural language processing (Computational linguistics)',
  'Computer vision ',
  'Expert systems',
  'Robotics ',
  'Computing in mathematics, natural sciences, engineering, and medicine',
  'Numerical analysis',
  'Algebraic (symbolic) computation',
  'Computational number theory',
  'Computational mathematics',
  'Scientific computing (Computational science)',
  'Computational biology (bioinformatics)',
  'Computational physics',
  'Computational chemistry',
  'Computational neuroscience',
  'Computer-aided engineering',
  'Finite element analysis',
  'Computational fluid dynamics',
  'Computing in social sciences, arts, humanities, and professions',
  'Computational economics',
  'Computational sociology',
  'Computational finance',
  'Digital humanities (Humanities computing)',
  'History of computer hardware',
  'History of computer science ',
  'Humanistic informatics',
  'Community informatics',
  'Logic',
  'Mathematical logic',
  'Set theory',
  'Proof theory',
  'Model theory',
  'Recursion theory',
  'Modal logic',
  'Intuitionistic logic',
  'Philosophical logic',
  'Logical reasoning',
  'Modal logic',
  'Deontic logic',
  'Doxastic logic',
  'Logic in computer science',
  'Programming language semantics',
  'Formal methods (Formal verification)',
  'Type theory',
  'Logic programming',
  'Multi-valued logic',
  'Fuzzy logic',
  'Mathematics',
  'Pure mathematics',
  'Algebra ',
  'Group theory',
  'Ring theory',
  'Commutative algebra',
  'Field theory',
  'Linear algebra (Vector space)',
  'Multilinear algebra',
  'Universal algebra',
  'Homological algebra',
  'Differential algebra',
  'Lattice theory (Order theory)',
  'Representation theory',
  'K-theory',
  'Category theory',
  'Topos theory',
  'Analysis',
  'Real analysis',
  'Calculus ',
  'Complex analysis',
  'Functional analysis',
  'Operator theory',
  'Non-standard analysis',
  'Harmonic analysis',
  'Fourier analysis',
  'p-adic analysis',
  'Ordinary differential equations',
  'Partial differential equations',
  'Probability theory',
  'Measure theory',
  'Integral geometry',
  'Ergodic theory',
  'Stochastic process',
  'Geometry ',
  'General topology',
  'Algebraic topology',
  'Geometric topology',
  'Differential topology',
  'Algebraic geometry',
  'Projective geometry',
  'Affine geometry',
  'Non-Euclidean geometry',
  'Convex geometry',
  'Discrete geometry',
  'Integral geometry',
  'Euclidean geometry',
  'Finite geometry',
  'Galois geometry',
  'Noncommutative geometry',
  'Solid geometry',
  'Trigonometry',
  'Number theory',
  'Analytic number theory',
  'Algebraic number theory',
  'Geometric number theory',
  'Arithmetic',
  'Arithmetic combinatorics',
  'Logic and Foundations of mathematics',
  'Set theory',
  'Proof theory',
  'Model theory',
  'Recursion theory',
  'Modal logic',
  'Intuitionistic logic',
  'Applied mathematics',
  'Approximation theory',
  'Computational mathematics',
  'Numerical analysis',
  'Operations research',
  'Mathematical optimization',
  'Linear programming',
  'Dynamic programming',
  'Assignment problem',
  'Decision analysis',
  'Inventory theory',
  'Scheduling',
  'Real options analysis',
  'Systems analysis',
  'Stochastic processes',
  'Optimal maintenance',
  'Dynamical systems',
  'Chaos theory',
  'Fractal geometry',
  'Mathematical physics',
  'Quantum mechanics',
  'Quantum field theory',
  'Quantum gravity',
  'String theory',
  'Statistical mechanics',
  'Theory of computation',
  'Computational complexity theory',
  'Information theory',
  'Cryptography',
  'Steganography',
  'Combinatorics ',
  'Coding theory',
  'Graph theory',
  'Game theory',
  'Statistics',
  'Mathematical statistics',
  'Econometrics',
  'Actuarial science',
  'Demography',
  'Computational statistics',
  'Data mining',
  'Regression ',
  'Simulation',
  'Bootstrap (statistics)',
  'Design of experiments',
  'Block design and Analysis of variance',
  'Response surface methodology',
  'Sample Survey',
  'Sampling theory',
  'Statistical modelling',
  'Biostatistics',
  'Epidemiology',
  'Multivariate analysis',
  'Structural equation model',
  'Time series',
  'Reliability theory',
  'Quality control',
  'Statistical theory',
  'Decision theory',
  'Mathematical statistics',
  'Probability ',
  'Survey methodology',
  'Systems science',
  'Network science',
  'Chaos theory',
  'Conceptual systems',
  'Communications system',
  'Complex systems',
  'Complex system',
  'Cybernetics',
  'Biocybernetics',
  'Engineering cybernetics',
  'Management cybernetics',
  'Medical cybernetics',
  'New cybernetics',
  'Second-order cybernetics',
  'Sociocybernetics',
  'Control theory',
  'Affect control theory',
  'Control engineering',
  'Control systems',
  'Dynamical systems',
  'Perceptual control theory',
  'Operations research',
  'Systems biology',
  'Computational systems biology',
  'Synthetic biology',
  'Systems immunology',
  'Systems neuroscience',
  'Systems chemistry',
  'System dynamics',
  'Social dynamics',
  'Systems ecology',
  'Ecosystem ecology',
  'Systems engineering',
  'Biological systems engineering',
  'Earth systems engineering and management',
  'Enterprise systems engineering',
  'Systems analysis',
  'Systems theory in anthropology',
  'Systems psychology',
  'Ergonomics',
  'Family systems theory',
  'Systemic therapy',
  'Systems theory',
  'Biochemical systems theory',
  'Ecological systems theory',
  'Developmental systems theory',
  'General systems theory',
  'Living systems theory',
  'LTI system theory',
  'Sociotechnical systems theory',
  'Mathematical system theory',
  'World-systems theory',
  'Professions and applied sciences',
  'Agriculture',
  'Agroecology',
  'Agronomy',
  'Animal husbandry (Animal science)',
  'Beekeeping (Apiculture)',
  'Agrology',
  'Entomology',
  'Agricultural economics',
  'Agricultural engineering',
  'Biological systems engineering',
  'Food engineering',
  'Aquaculture',
  'Enology',
  'Food science',
  'Horticulture',
  'Culinary arts',
  'Hydrology ',
  'Pedology',
  'Plant science ',
  'Pomology',
  'Pest control',
  'Purification',
  'Viticulture',
  'Architecture and design',
  'Architecture ',
  'Interior architecture',
  'Landscape architecture',
  'Architectural analytics',
  'Historic preservation',
  'Interior design (interior architecture)',
  'Landscape architecture (landscape planning)',
  'Landscape design',
  'Urban planning (urban design)',
  'Visual communication',
  'Graphic design',
  'Type design',
  'Technical drawing',
  'Industrial design (product design)',
  'Ergonomics ',
  'Toy and amusement design',
  'User experience design',
  'Interaction design',
  'Information architecture',
  'User interface design',
  'User experience evaluation',
  'Decorative arts',
  'Fashion design',
  'Textile design',
  'Business',
  'Accounting',
  'Accounting research',
  'Accounting scholarship',
  'Business administration',
  'Business analysis',
  'Business ethics',
  'Business law',
  'E-Business',
  'Entrepreneurship',
  'Finance ',
  'Industrial and labor relations',
  'Collective bargaining',
  'Human resources',
  'Organizational studies',
  'Labor economics',
  'Labor history',
  'Information systems (Business informatics)',
  'Management information systems',
  'Health informatics',
  'Information technology ',
  'International trade',
  'Management ',
  'Marketing ',
  'Operations management',
  'Purchasing',
  'Risk management and insurance',
  'Systems science',
  'Divinity',
  'Canon law',
  'Church history',
  'Field ministry',
  'Pastoral counseling',
  'Pastoral theology',
  'Religious education techniques',
  'Homiletics',
  'Liturgy',
  'Sacred music',
  'Missiology',
  'Hermeneutics',
  'Scriptural study and languages',
  'Biblical Hebrew',
  'Biblical studies/Sacred scripture',
  'Vedic Study',
  'New Testament Greek',
  'Latin',
  'Old Church Slavonic',
  'Theology ',
  'Dogmatic theology',
  'Ecclesiology',
  'Sacramental theology',
  'Systematic theology',
  'Christian ethics',
  'Hindu ethics',
  'Moral theology',
  'Historical theology',
  'Education',
  'Comparative education',
  'Critical pedagogy',
  'Curriculum and instruction',
  'Alternative education',
  'Early childhood education',
  'Elementary education',
  'Secondary education',
  'Higher education',
  'Mastery learning',
  'Cooperative learning',
  'Agricultural education',
  'Art education',
  'Bilingual education',
  'Chemistry education',
  'Counselor education',
  'Language education',
  'Legal education',
  'Mathematics education',
  'Medical education',
  'Military education and training',
  'Music education',
  'Nursing education',
  'Outdoor education',
  'Peace education',
  'Physical education/Sports coaching',
  'Physics education',
  'Reading education',
  'Religious education',
  'Science education',
  'Special education',
  'Sex education',
  'Sociology of education',
  'Technology education',
  'Vocational education',
  'Educational leadership',
  'Educational philosophy',
  'Educational psychology',
  'Educational technology',
  'Distance education',
  'Engineering and technology',
  'Chemical engineering',
  'Biocatalysts',
  'Bioengineering',
  'Biochemical engineering',
  'Biomolecular engineering',
  'Bionics',
  'Catalysis',
  'Materials engineering',
  'Molecular engineering',
  'Nanotechnology',
  'Polymer engineering',
  'Process design',
  'Petroleum engineering',
  'Nuclear engineering',
  'Food engineering',
  'Process engineering',
  'Reaction engineering',
  'Thermodynamics',
  'Transport phenomena',
  'Civil engineering',
  'Agricultural engineering',
  'Coastal engineering',
  'Construction',
  'Earthquake engineering',
  'Ecological engineering',
  'Environmental engineering',
  'Geotechnical engineering',
  'Engineering geology',
  'Hydraulic engineering',
  'Infrastructure',
  'Mining engineering',
  'Transportation engineering',
  'Highway engineering',
  'Structural engineering',
  'Architectural engineering',
  'Structural mechanics',
  'Surveying',
  'Electrical engineerin',
  'Applied physics',
  'Computer engineering ',
  'Computer science',
  'Control systems engineering',
  'Control theory',
  'Electronic engineering',
  'Electronics',
  'Instrumentation engineering',
  'Engineering physics',
  'Photonics',
  'Information theory',
  'Mechatronics',
  'Power engineering',
  'Robotics ',
  'Microbotics',
  'Semiconductors',
  'Telecommunications engineering',
  'Quantum computing',
  'Materials science and engineering',
  'Biomaterials',
  'Ceramic engineering',
  'Corrosion engineering',
  'Crystallography',
  'Nanomaterials',
  'Photonics',
  'Physical metallurgy',
  'Polymer engineering',
  'Polymer science',
  'Semiconductors',
  'Mechanical engineering',
  'Aerospace engineering',
  'Aeronautics',
  'Astronautics',
  'Acoustical engineering',
  'Automotive engineering',
  'Biomedical engineering',
  'Biomechanical engineering',
  'Continuum mechanics',
  'Fluid mechanics',
  'Heat transfer',
  'Industrial engineering',
  'Manufacturing engineering',
  'Marine engineering',
  'Mass transfer',
  'Mechatronics',
  'Nanoengineering',
  'Ocean engineering',
  'Optical engineering',
  'Robotics',
  'Thermal engineering',
  'Thermodynamics',
  'Environmental studies and forestry',
  'Environmental management',
  'Coastal management',
  'Fisheries management',
  'Land management',
  'Natural resource management',
  'Waste management',
  'Wildlife management',
  'Environmental policy',
  'Wildlife observation',
  'Recreation ecology',
  'Silviculture',
  'Sustainability studies',
  'Sustainable development',
  'Toxicology',
  'Ecology',
  'Family and consumer science',
  'Consumer education',
  'Housing',
  'Interior design',
  'Nutrition ',
  'Foodservice management',
  'Textiles',
  'Human physical performance and recreation',
  'Biomechanics / Sports biomechanics',
  'Sports coaching',
  'Escapology',
  'Ergonomics',
  'Physical fitness',
  'Aerobics',
  'Personal trainer / Personal fitness training',
  'Game design',
  'Exercise physiology',
  'Kinesiology / Exercise physiology / Performance science',
  'Leisure studies',
  'Navigation',
  'Outdoor activity',
  'Physical activity',
  'Physical education / Pedagogy',
  'Sociology of sport',
  'Sexology',
  'Sports / exercise',
  'Sports journalism / sportscasting',
  'Sport management',
  'Athletic director',
  'Sport psychology',
  'Sports medicine',
  'Athletic training',
  'Survival skills',
  'Batoning',
  'Bushcraft',
  'Scoutcraft',
  'Woodcraft',
  'Toy and amusement design',
  'Journalism, media studies and communication',
  'Journalism ',
  'Broadcast journalism',
  'Digital journalism',
  'Literary journalism',
  'New media journalism',
  'Print journalism',
  'Sports journalism / sportscasting',
  'Media studies (Mass media)',
  'Newspaper',
  'Magazine',
  'Radio ',
  'Television ',
  'Television studies',
  'Film ',
  'Film studies',
  'Game studies **',
  'Narratology',
  'Internet ',
  'Communication studies',
  'Advertising',
  'Animal communication',
  'Communication design',
  'Conspiracy theory',
  'Digital media',
  'Electronic media',
  'Environmental communication',
  'Hoax',
  'Information theory',
  'Intercultural communication',
  'Marketing ',
  'Mass communication',
  'Nonverbal communication',
  'Organizational communication',
  'Popular culture studies',
  'Propaganda',
  'Public relations ',
  'Speech communication',
  'Technical writing',
  'Translation',
  'Law',
  'Legal management',
  'Corporate law',
  'Mercantile law',
  'Business law',
  'Administrative law',
  'Canon law',
  'Comparative law',
  'Constitutional law',
  'Competition law',
  'Criminal law',
  'Criminal procedure',
  'Criminal justice ',
  'Police science',
  'Forensic science ',
  'Islamic law',
  'Jewish law ',
  'Jurisprudence (Philosophy of Law)',
  'Civil law',
  'Admiralty law',
  'Animal law/Animal rights',
  'Common law',
  'Corporations',
  'Civil procedure',
  'Contract law',
  'Environmental law',
  'Family law',
  'Federal law',
  'International law',
  'Public international law',
  'Supranational law',
  'Labor law',
  'Paralegal studies',
  'Property law',
  'Tax law',
  'Tort law ',
  'Law enforcement ',
  'Procedural law',
  'Substantive law',
  'Library and museum studies',
  'Archival science',
  'Archivist',
  'Bibliographic databases',
  'Bibliometrics',
  'Bookmobile',
  'Cataloging',
  'Citation analysis',
  'Categorization',
  'Classification',
  'Library classification',
  'Taxonomic classification',
  'Scientific classification',
  'Statistical classification',
  'Security classification',
  'Film classification',
  'Collections care',
  'Collection management',
  'Collection Management Policy',
  'Conservation science',
  'Conservation and restoration of cultural heritage',
  'Curator',
  'Data storage',
  'Database management',
  'Data modeling',
  'Digital preservation',
  'Dissemination',
  'Film preservation',
  'Five laws of library science',
  'Historic preservation',
  'History of library science',
  'Human-computer interaction',
  'Indexer',
  'Informatics',
  'Information architecture',
  'Information broker',
  'Information literacy',
  'Information retrieval',
  'Information science ',
  'Information systems and technology',
  'Integrated library system',
  'Interlibrary loan',
  'Knowledge engineering',
  'Knowledge management',
  'Library',
  'Library binding',
  'Library circulation',
  'Library instruction',
  'Library portal',
  'Library technical services',
  'Management',
  'Mass deacidification',
  'Museology',
  'Museum education',
  'Museum administration',
  'Object conservation',
  'Preservation',
  'Prospect research',
  "Readers' advisory",
  'Records management',
  'Reference',
  'Reference desk',
  'Reference management software',
  'Registrar',
  'Research methods',
  'Slow fire',
  'Special library',
  'Statistics',
  'Medicine',
  'Alternative medicine',
  'Cleaning',
  'Clinical laboratory sciences/Clinical pathology/Laboratory medicine',
  'Clinical biochemistry',
  'Cytogenetics',
  'Cytohematology',
  'Cytology ',
  'Haemostasiology',
  'Histology',
  'Clinical immunology',
  'Clinical microbiology',
  'Molecular genetics',
  'Parasitology',
  'Clinical physiology',
  'Cosmetology',
  'Decontamination',
  'Dentistry ',
  'Dental hygiene and epidemiology',
  'Dental surgery',
  'Endodontics',
  'Orthodontics',
  'Oral and maxillofacial surgery',
  'Periodontics',
  'Prosthodontics',
  'Implantology',
  'Dermatology',
  'Emergency medicine ',
  'Health informatics/Clinical informatics',
  'Music therapy',
  'Nursing',
  'Nutrition ',
  'Optometry',
  'Orthoptics',
  'Osteopathy',
  'Physiotherapy',
  'Occupational therapy',
  'Speech and language pathology',
  'Internal medicine',
  'Preventive medicine',
  'Cardiology',
  'Cardiac electrophysiology',
  'Dermatology',
  'Pulmonology',
  'Medical toxicology',
  'Endocrinology',
  'Gastroenterology',
  'Hepatology',
  'Oncology',
  'Geriatrics',
  'Gynaecology',
  'Hematology',
  'Infectious disease',
  'Nephrology',
  'Neurology',
  'Neurosurgery',
  'Obstetrics ',
  'Ophthalmology',
  'Neuro-ophthalmology',
  'Orthopedic surgery',
  'Otolaryngology',
  'Pathology',
  'Pediatrics',
  'Pharmacy',
  'Pharmaceutical sciences',
  'Pharmacognosy',
  'Physical fitness',
  'Aerobics',
  'Personal fitness training',
  'Kinesiology / Exercise physiology / Performance science',
  'Physical therapy',
  'Podiatry',
  'Primary care',
  'General practice',
  'Psychiatry ',
  'Psychology ',
  'Psychosomatic',
  'Psychotherapy',
  'Public health',
  'Radiology',
  'Recreation therapy',
  'Rehabilitation medicine',
  'Respiratory medicine',
  'Pulmonology',
  'Sleep medicine',
  'Respiratory therapy',
  'Rheumatology',
  'Sports medicine',
  'Sterilization (microbiology)',
  'Surgery',
  'Bariatric surgery',
  'Cardiothoracic surgery',
  'Neurosurgery',
  'Plastic surgery',
  'Trauma surgery',
  'Traumatology',
  'Traditional medicine',
  'Therapy',
  'Urology',
  'Andrology',
  'Veterinary medicine',
  'Military sciences',
  'Amphibious warfare',
  'Artillery',
  'Battlespace',
  'Air',
  'Information',
  'Land',
  'Sea',
  'Space',
  'Campaigning',
  'Military engineering',
  'Doctrine',
  'Espionage',
  'Game theory',
  'Grand strategy',
  'Containment',
  'Limited war',
  'Military science ',
  'Philosophy of war',
  'Strategic studies',
  'Total war',
  'War ',
  'Leadership',
  'Logistics',
  'Materiel',
  'Supply chain management',
  'Military operation',
  'Military history',
  'Prehistoric',
  'Ancient',
  'Medieval',
  'Early modern',
  'Industrial',
  'Modern',
  'Fourth-generation warfare',
  'Military intelligence',
  'Military law',
  'Military medicine',
  'Naval science',
  'Naval engineering',
  'Naval tactics',
  'Naval architecture',
  'Organization',
  'Command and control',
  'Doctrine',
  'Education and training',
  'Engineers',
  'Intelligence',
  'Ranks',
  'Staff',
  'Technology and equipment',
  'Military exercises',
  'Military simulation',
  'Military sports',
  'Strategy',
  'Attrition',
  'Deception',
  'Defensive',
  'Offensive',
  'Counter-offensive',
  'Maneuver',
  'Goal',
  'Naval',
  'Tactics',
  'Aerial',
  'Battle',
  'Cavalry',
  'Charge',
  'Counter-attack',
  'Counter-insurgency',
  'Counter-intelligence',
  'Counter-terrorism',
  'Foxhole',
  'Endemic warfare',
  'Guerrilla warfare',
  'Infiltration',
  'Irregular warfare',
  'Morale',
  'Naval tactics',
  'Siege',
  'Surgical strike',
  'Tactical objective',
  'Trench warfare',
  'Military weapons',
  'Armor',
  'Artillery',
  'Biological',
  'Cavalry',
  'Conventional',
  'Chemical',
  'Cyber',
  'Economic',
  'Electronic',
  'Infantry',
  'Nuclear',
  'Psychological',
  'Unconventional',
  'Other Military',
  'Arms control',
  'Arms race',
  'Assassination',
  'Asymmetric warfare',
  'Civil defense',
  'Clandestine operation',
  'Collateral damage',
  'Cold war (general term)',
  'Combat',
  'Covert operation',
  'Cyberwarfare',
  'Defense industry',
  'Disarmament',
  'Intelligence agency',
  'Laws of war',
  'Mercenary',
  'Military campaign',
  'Military operation',
  'Mock combat',
  'Network-centric warfare',
  'Paramilitary',
  'Principles of war',
  'Private defense agency',
  'Private military company',
  'Proxy war',
  'Religious war',
  'Security',
  'Special forces',
  'Special operations',
  'Theater (warfare)',
  'Theft',
  'Undercover',
  'War crimes',
  'Warrior',
  'Public administration',
  'Civil service',
  'Corrections',
  'Conservation biology',
  'Criminal justice ',
  'Disaster research',
  'Disaster response',
  'Emergency management',
  'Emergency services',
  'Fire safety (Structural fire protection)',
  'Fire ecology (Wildland fire management)',
  'Governmental affairs',
  'International affairs',
  'Law enforcement',
  'Peace and conflict studies',
  'Police science',
  'Policy studies',
  'Policy analysis',
  'Public administration',
  'Nonprofit administration',
  'Non-governmental organization (NGO) administration',
  'Public policy doctrine',
  'Public policy school',
  'Regulation',
  'Public safety',
  'Public service',
  'Public policy',
  'Agricultural policy',
  'Commercial policy',
  'Cultural policy',
  'Domestic policy',
  'Drug policy',
  'Drug policy reform',
  'Economic policy',
  'Fiscal policy',
  'Incomes policy',
  'Industrial policy',
  'Investment policy',
  'Monetary policy',
  'Tax policy',
  'Education policy',
  'Energy policy',
  'Nuclear energy policy',
  'Renewable energy policy',
  'Environmental policy',
  'Food policy',
  'Foreign policy',
  'Health policy',
  'Pharmaceutical policy',
  'Vaccination policy',
  'Housing policy',
  'Immigration policy',
  'Knowledge policy',
  'Language policy',
  'Military policy',
  'Science policy',
  'Climate change policy',
  'Stem cell research policy',
  'Space policy',
  'Technology policy',
  'Security policy',
  'Social policy',
  'Public policy by country',
  'Social work',
  'Child welfare',
  'Community practice',
  'Community organizing',
  'Social policy',
  'Human Services',
  'Corrections',
  'Gerontology',
  'Medical social work',
  'Mental health',
  'School social work',
  'Transportation',
  'Highway safety',
  'Infographics',
  'Intermodal transportation studies',
  'Logistics',
  'Marine transportation',
  'Port management',
  'Seafaring',
  'Operations research',
  'Mass transit',
  'Travel',
  'Vehicles'
];
